MLIR: mlir::linalg::BufferizationAliasInfo Class Reference
mlir::linalg::BufferizationAliasInfo Class Reference
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
#include "mlir/Dialect/Linalg/Transforms/ComprehensiveBufferize.h"
Public Types
enum BufferRelation { BufferRelation::None, BufferRelation::Equivalent }
Specify fine-grain relationship between buffers to enable more analysis.
Public Member Functions
BufferizationAliasInfo (Operation *rootOp)
void createAliasInfoEntry (Value v)
Add a new entry for v in the aliasInfo and equivalentInfo.
void insertNewBufferAlias (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
void insertNewBufferEquivalence (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
bool aliasesNonWritableBuffer (Value value) const
Return true if, under current bufferization decisions, the buffer of value is not writable.
bool aliasesInPlaceWrite (Value v) const
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
void bufferizeInPlace (OpResult result, OpOperand &operand)
Set the inPlace bufferization spec to true.
void bufferizeOutOfPlace (OpResult result)
Set the inPlace bufferization spec to false.
bool hasMatchingExtractSliceOp (Value value, tensor::InsertSliceOp insertOp) const
Return true if value has an ExtractSliceOp matching the given InsertSliceOp in its reverse SSA use-def chain.
bool wouldCreateWriteToNonWritableBuffer (OpOperand &opOperand, OpResult opResult) const
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
bool wouldCreateReadAfterWriteInterference (OpOperand &operand, OpResult result, const DominanceInfo &domInfo) const
Assume that result bufferizes in-place with one of the operation's operands.
bool areEquivalentBufferizedValues (Value v1, Value v2) const
Return true if v1 and v2 bufferize to equivalent buffers.
bool isSourceEquivalentToAMatchingInplaceExtractSliceOp (tensor::InsertSliceOp insertSliceOp) const
Return true if the source of an insertSliceOp bufferizes to an equivalent ExtractSliceOp.
void applyOnEquivalenceClass (Value v, function_ref< void(Value)> fun) const
Apply fun to all the members of the equivalence class of v.
bool bufferizesToWritableMemory (Value v) const
Return true if the value is known to bufferize to writable memory.
void setBufferizesToWritableMemory (Value v)
Specify that the value is known to bufferize to writable memory.
void printAliases (raw_ostream &os) const
Print to os.
void printEquivalences (raw_ostream &os) const
void dumpAliases () const
Print to errs().
void dumpEquivalences () const
Detailed Description
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
ExtractSliceOps have special behavior, they act as a level of indirection for bufferization. They don't create reads or writes themselves and analysis needs to look through their uses. ExtractSliceOp + InsertSliceOp have special joint behavior: they may bufferize to the same buffer (i.e. subview), which is what introduces the need for bufferization classes. Some of these functionalities could be refactored in a Bufferizer class that uses BufferizationAliasInfo.
Definition at line 35 of file ComprehensiveBufferize.h.
Member Enumeration Documentation
BufferRelation
enum mlir::linalg::BufferizationAliasInfo::BufferRelation strong
Specify fine-grain relationship between buffers to enable more analysis.
Enumerator
None
Equivalent
Definition at line 38 of file ComprehensiveBufferize.h.
Constructor & Destructor Documentation
BufferizationAliasInfo()
BufferizationAliasInfo::BufferizationAliasInfo (Operation * rootOp) explicit
Definition at line 734 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getRegions(), mlir::Operation::getResults(), and mlir::Operation::walk().
Member Function Documentation
aliasesInPlaceWrite()
bool BufferizationAliasInfo::aliasesInPlaceWrite (Value value) const
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
Definition at line 827 of file ComprehensiveBufferize.cpp.
References isInplaceMemoryWrite(), LDBG, printOperationInfo(), and printValueInfo().
aliasesNonWritableBuffer()
bool BufferizationAliasInfo::aliasesNonWritableBuffer (Value value) const
Return true if, under current bufferization decisions, the buffer of value is not writable.
Definition at line 784 of file ComprehensiveBufferize.cpp.
References getInPlace(), hasKnownBufferizationAliasingBehavior(), LDBG, printValueInfo(), and True.
applyOnEquivalenceClass()
void BufferizationAliasInfo::applyOnEquivalenceClass (Value v, function_ref< void(Value)> fun) const
Apply fun to all the members of the equivalence class of v.
Definition at line 1218 of file ComprehensiveBufferize.cpp.
Referenced by areEquivalentBufferizedValues().
areEquivalentBufferizedValues()
bool mlir::linalg::BufferizationAliasInfo::areEquivalentBufferizedValues (Value v1, Value v2) const inline
Return true if v1 and v2 bufferize to equivalent buffers.
Definition at line 92 of file ComprehensiveBufferize.h.
References applyOnEquivalenceClass(), mlir::linalg::bufferizeOp(), bufferizesToWritableMemory(), dumpAliases(), dumpEquivalences(), mlir::Value::getImpl(), mlir::linalg::inPlaceAnalysis(), isSourceEquivalentToAMatchingInplaceExtractSliceOp(), mlir::operator<(), mlir::operator==(), printAliases(), printEquivalences(), setBufferizesToWritableMemory(), and wrap().
Referenced by bufferize(), and getEquivalentEnclosingFuncBBArg().
bufferizeInPlace()
void BufferizationAliasInfo::bufferizeInPlace (OpResult result, OpOperand & operand)
Set the inPlace bufferization spec to true.
Merge result's and operand's aliasing sets and iterate to a fixed point.
Definition at line 844 of file ComprehensiveBufferize.cpp.
References bufferRelation(), mlir::IROperand< DerivedT, IRValueT >::get(), setInPlaceOpResult(), and True.
Referenced by bufferizableInPlaceAnalysisImpl().
bufferizeOutOfPlace()
void BufferizationAliasInfo::bufferizeOutOfPlace (OpResult result)
Set the inPlace bufferization spec to false.
Definition at line 857 of file ComprehensiveBufferize.cpp.
References False, and setInPlaceOpResult().
Referenced by bufferizableInPlaceAnalysisImpl().
bufferizesToWritableMemory()
bool BufferizationAliasInfo::bufferizesToWritableMemory (Value v) const
Return true if the value is known to bufferize to writable memory.
Definition at line 816 of file ComprehensiveBufferize.cpp.
Referenced by areEquivalentBufferizedValues().
createAliasInfoEntry()
void BufferizationAliasInfo::createAliasInfoEntry (Value v)
Add a new entry for v in the aliasInfo and equivalentInfo.
In the beginning the alias and equivalence sets only contain v itself.
Definition at line 762 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), createNewAllocDeallocPairForShapedValue(), and runInitTensorElimination().
dumpAliases()
void BufferizationAliasInfo::dumpAliases () const
Print to errs().
Definition at line 1277 of file ComprehensiveBufferize.cpp.
Referenced by areEquivalentBufferizedValues().
dumpEquivalences()
void BufferizationAliasInfo::dumpEquivalences () const
Definition at line 1279 of file ComprehensiveBufferize.cpp.
References getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), mlir::isEqualConstantIntOrValue(), and sameOffsetsSizesAndStrides().
Referenced by areEquivalentBufferizedValues().
hasMatchingExtractSliceOp()
bool BufferizationAliasInfo::hasMatchingExtractSliceOp (Value value, tensor::InsertSliceOp insertOp) const
Return true if value has an ExtractSliceOp matching the given InsertSliceOp in its reverse SSA use-def chain.
Return true if value is originating from an ExtractSliceOp that matches the given InsertSliceOp.
Definition at line 947 of file ComprehensiveBufferize.cpp.
References findValueInReverseUseDefChain().
insertNewBufferAlias()
void BufferizationAliasInfo::insertNewBufferAlias (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
Definition at line 769 of file ComprehensiveBufferize.cpp.
Referenced by bufferize().
insertNewBufferEquivalence()
void BufferizationAliasInfo::insertNewBufferEquivalence (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
Additionally, merge their equivalence classes.
Definition at line 776 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), bufferizeFuncOpBoundary(), and createNewAllocDeallocPairForShapedValue().
isSourceEquivalentToAMatchingInplaceExtractSliceOp()
bool BufferizationAliasInfo::isSourceEquivalentToAMatchingInplaceExtractSliceOp (tensor::InsertSliceOp insertSliceOp) const
Return true if the source of an insertSliceOp bufferizes to an equivalent ExtractSliceOp.
Return true if the source of a insertSliceOp bufferizes to an equivalent ExtractSliceOp that bufferizes inplace.
Definition at line 1197 of file ComprehensiveBufferize.cpp.
References getInPlace(), LDBG, and True.
Referenced by areEquivalentBufferizedValues(), and bufferize().
printAliases()
void BufferizationAliasInfo::printAliases (raw_ostream & os) const
Print to os.
Definition at line 1227 of file ComprehensiveBufferize.cpp.
References printValueInfo().
Referenced by areEquivalentBufferizedValues().
printEquivalences()
void BufferizationAliasInfo::printEquivalences (raw_ostream & os) const
Definition at line 1245 of file ComprehensiveBufferize.cpp.
References printValueInfo().
Referenced by areEquivalentBufferizedValues().
setBufferizesToWritableMemory()
void BufferizationAliasInfo::setBufferizesToWritableMemory (Value v)
Specify that the value is known to bufferize to writable memory.
Definition at line 821 of file ComprehensiveBufferize.cpp.
Referenced by areEquivalentBufferizedValues(), and inPlaceAnalysisFuncOpBody().
wouldCreateReadAfterWriteInterference()
bool BufferizationAliasInfo::wouldCreateReadAfterWriteInterference (OpOperand & operand, OpResult result, const DominanceInfo & domInfo) const
Assume that result bufferizes in-place with one of the operation's operands.
Return true if bufferizing result inplace would create a conflict.
Return true if it is possible to find an inplace write W that creates a conflict.
A read R and a write W of the same alias set is a conflict if inplace bufferization of W changes the value read by R to a value different from the one that would be expected by tracing back R's origin through SSA use-def chains. A conflict can only be introduced by a new alias and/or an inplace bufferization decision.
Example: %0 = tensor.extract_slice t[...][...][1, 1] {inplace?} %1 = vector.transfer_write v1, t {inplace} : vector<5xf32>, tensor<?xf32> e = tensor.extract_slice %1 %2 = vector.transfer_write v2, %0 {inplace} : vector<6xf32>, tensor<?xf32> %3 = vector.transfer_read e, cst : tensor<?xf32>, vector<7xf32>
In the above example, the two TransferWriteOps have already been decided to bufferize inplace. Bufferizing the ExtractSliceOp inplace would create a conflict because:
According to SSA use-def chains, we expect to read the result of %1.
However, adding an alias {%0, t} would mean that the second TransferWriteOp overwrites the first one. Therefore, the TransferReadOp would no longer be reading the result of %1.
Definition at line 1127 of file ComprehensiveBufferize.cpp.
References getAliasingOpOperand().
Referenced by bufferizableInPlaceAnalysisImpl().
wouldCreateWriteToNonWritableBuffer()
bool BufferizationAliasInfo::wouldCreateWriteToNonWritableBuffer (OpOperand & opOperand, OpResult opResult) const
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
Definition at line 1167 of file ComprehensiveBufferize.cpp.
References bufferizesToMemoryWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpOperand(), and LDBG.
Referenced by bufferizableInPlaceAnalysisImpl().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/ComprehensiveBufferize.h
lib/Dialect/Linalg/Transforms/ComprehensiveBufferize.cpp