MLIR: mlir::python::PyValue Class Reference
mlir::python::PyValue Class Reference
Wrapper around the generic MlirValue.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PyValue (PyOperationRef parentOperation, MlirValue value)
operator MlirValue () const
MlirValue get ()
PyOperationRef & getParentOperation ()
void checkValid ()
pybind11::object getCapsule ()
Gets a capsule wrapping the void* within the MlirValue.
Static Public Member Functions
static PyValue createFromCapsule (pybind11::object capsule)
Creates a PyValue from the MlirValue wrapped by a capsule.
Detailed Description
Wrapper around the generic MlirValue.
Values are managed completely by the operation that resulted in their definition. For op result value, this is the operation that defines the value. For block argument values, this is the operation that contains the block to which the value is an argument (blocks cannot be detached in Python bindings so such operation always exists).
Definition at line 767 of file IRModule.h.
Constructor & Destructor Documentation
PyValue()
mlir::python::PyValue::PyValue (PyOperationRef parentOperation, MlirValue value) inline
Definition at line 769 of file IRModule.h.
Member Function Documentation
checkValid()
void mlir::python::PyValue::checkValid () inline
Definition at line 776 of file IRModule.h.
References value.
createFromCapsule()
PyValue PyValue::createFromCapsule (pybind11::object capsule) static
Creates a PyValue from the MlirValue wrapped by a capsule.
Ownership of the underlying MlirValue is still tied to the owning operation.
Definition at line 1498 of file IRCore.cpp.
References mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), MlirNamedAttribute::attribute, PyGlobalDebugFlag::bind(), mlir::python::PyOpView::buildGeneric(), mlir::python::PyOperation::checkValid(), mlir::python::PyRegion::checkValid(), classmethod(), mlir::python::PyMlirContext::contextEnter(), mlir::python::PyLocation::contextEnter(), mlir::python::PyInsertionPoint::contextEnter(), mlir::python::PyMlirContext::contextExit(), mlir::python::PyLocation::contextExit(), mlir::python::PyInsertionPoint::contextExit(), mlir::python::PyOperation::create(), createCustomDialectWrapper(), mlir::python::PyMlirContext::createFromCapsule(), mlir::python::PyLocation::createFromCapsule(), mlir::python::PyModule::createFromCapsule(), mlir::python::PyOperation::createFromCapsule(), mlir::python::PyAttribute::createFromCapsule(), mlir::python::PyType::createFromCapsule(), mlir::python::PyMlirContext::createNewContextForInit(), mlir::python::PyOperation::createOpView(), MlirStringRef::data, mlir::python::PyOperation::erase(), mlir::python::PyMlirContext::forContext(), mlir::python::PyModule::forModule(), mlir::python::PyOperation::forOperation(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::PyLocation::get(), mlir::python::PyOperation::get(), mlir::python::PyRegion::get(), mlir::python::PyBlock::get(), get(), mlir::python::PyOperationBase::getAsm(), mlir::PyPrintAccumulator::getCallback(), mlir::python::PyMlirContext::getCapsule(), mlir::python::PyLocation::getCapsule(), mlir::python::PyModule::getCapsule(), mlir::python::PyOperation::getCapsule(), mlir::python::PyAttribute::getCapsule(), mlir::python::PyType::getCapsule(), getCapsule(), mlir::python::BaseContextObject::getContext(), mlir::python::PyThreadContextEntry::getDefaultContext(), mlir::python::PyThreadContextEntry::getDefaultInsertionPoint(), mlir::python::PyThreadContextEntry::getDefaultLocation(), mlir::python::PyMlirContext::getLiveCount(), mlir::python::PyMlirContext::getLiveModuleCount(), mlir::python::PyMlirContext::getLiveOperationCount(), mlir::python::PyOperationBase::getOperation(), mlir::python::PyOperation::getOperation(), mlir::python::PyOpView::getOperationObject(), mlir::python::PyRegion::getParentOperation(), getParentOperation(), mlir::PyPrintAccumulator::getUserData(), mlir::python::PyInsertionPoint::insert(), mlir::PyPrintAccumulator::join(), kContextGetCallSiteLocationDocstring, kContextGetFileLocationDocstring, kContextGetNameLocationDocString, kContextParseTypeDocstring, kDumpDocstring, kModuleParseDocstring, kOperationCreateDocstring, kOperationGetAsmDocstring, kOperationPrintDocstring, kOperationStrDunderDocstring, kValueDunderStrDocstring, MlirStringRef::length, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirAttributeDump(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeIsNull(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBlockArgumentGetArgNumber(), mlirBlockArgumentGetOwner(), mlirBlockArgumentSetType(), mlirBlockCreate(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNumArguments(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockPrint(), mlirContextEnableMultithreading(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextIsRegisteredOperation(), mlirContextSetAllowUnregisteredDialects(), mlirDialectGetNamespace(), mlirDialectIsNull(), mlirIdentifierStr(), mlirLocationCallSiteGet(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationNameGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleGetBody(), mlirModuleGetOperation(), mlirModuleIsNull(), mlirOperationDump(), mlirOperationEqual(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetContext(), mlirOperationGetLocation(), mlirOperationGetName(), mlirOperationGetNumAttributes(), mlirOperationGetNumOperands(), mlirOperationGetNumResults(), mlirOperationGetOperand(), mlirOperationGetResult(), mlirOperationIsNull(), mlirOperationPrint(), mlirOperationRemoveAttributeByName(), mlirOperationSetAttributeByName(), mlirOperationSetOperand(), mlirOperationVerify(), mlirOpResultGetOwner(), mlirOpResultGetResultNumber(), mlirPythonCapsuleToValue(), mlirRegionGetFirstBlock(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), mlirTypeDump(), mlirTypeIsNull(), mlirTypeParseGet(), mlirTypePrint(), mlirValueDump(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValueIsNull(), mlirValuePrint(), MlirNamedAttribute::name, mlir::python::PyNamedAttribute::namedAttr, mlir::PyPrintAccumulator::parts, mlir::python::populateIRCore(), mlir::python::PyOperationBase::print(), mlir::python::PyNamedAttribute::PyNamedAttribute(), mlir::python::PyObjectRef< T >::releaseObject(), mlir::python::SetPyError(), toMlirStringRef(), and value.
get()
MlirValue mlir::python::PyValue::get () inline
Definition at line 773 of file IRModule.h.
References value.
Referenced by createFromCapsule().
getCapsule()
pybind11::object PyValue::getCapsule ()
Gets a capsule wrapping the void* within the MlirValue.
Definition at line 1494 of file IRCore.cpp.
References mlirPythonValueToCapsule().
Referenced by createFromCapsule().
getParentOperation()
PyOperationRef& mlir::python::PyValue::getParentOperation () inline
Definition at line 774 of file IRModule.h.
Referenced by createFromCapsule().
operator MlirValue()
mlir::python::PyValue::operator MlirValue () const inline
Definition at line 771 of file IRModule.h.
References value.
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp