MLIR: mlir::DenseElementsAttr Class Reference
mlir::DenseElementsAttr Class Reference
An attribute that represents a reference to a dense vector or tensor object.
#include "mlir/IR/BuiltinAttributes.h"
Classes
class AttributeElementIterator
A utility iterator that allows walking over the internal Attribute values of a DenseElementsAttr.
class BoolElementIterator
A utility iterator that allows walking over the internal bool values.
class ComplexFloatElementIterator
Iterator for walking over complex APFloat values.
class ComplexIntElementIterator
A utility iterator that allows walking over the internal raw complex APInt values.
class ElementIterator
Iterator for walking raw element values of the specified type 'T', which may be any c++ data type matching the stored representation: int32_t, float, etc.
class FloatElementIterator
Iterator for walking over APFloat values.
class IntElementIterator
A utility iterator that allows walking over the internal raw APInt values.
struct is_valid_cpp_fp_type
Type trait used to check if the given type T is a potentially valid C++ floating point type that can be used to access the underlying element types of a DenseElementsAttr.
Public Types
template<typename T >
using IntFloatValueTemplateCheckT = typename std::enable_if<(!std::is_same< T, bool >::value &&std::numeric_limits< T >::is_integer)||is_valid_cpp_fp_type< T >::value >::type
Return the held element values as a range of integer or floating-point values.
template<typename T , typename ElementT >
using ComplexValueTemplateCheckT = typename std::enable_if< detail::is_complex_t< T >::value &&(std::numeric_limits< ElementT >::is_integer||is_valid_cpp_fp_type< ElementT >::value)>::type
Return the held element values as a range of std::complex.
template<typename T >
using StringRefValueTemplateCheckT = typename std::enable_if< std::is_same< T, StringRef >::value >::type
Return the held element values as a range of StringRef.
template<typename T >
using AttributeValueTemplateCheckT = typename std::enable_if< std::is_same< T, Attribute >::value >::type
Return the held element values as a range of Attributes.
template<typename T >
using DerivedAttrValueTemplateCheckT = typename std::enable_if< std::is_base_of< Attribute, T >::value &&!std::is_same< Attribute, T >::value >::type
Return the held element values a range of T, where T is a derived attribute type.
template<typename T >
using DerivedAttributeElementIterator = llvm::mapped_iterator< AttributeElementIterator, T(*)(Attribute)>
template<typename T >
using BoolValueTemplateCheckT = typename std::enable_if< std::is_same< T, bool >::value >::type
Return the held element values as a range of bool.
template<typename T >
using APIntValueTemplateCheckT = typename std::enable_if< std::is_same< T, APInt >::value >::type
Return the held element values as a range of APInts.
template<typename T >
using ComplexAPIntValueTemplateCheckT = typename std::enable_if< std::is_same< T, std::complex< APInt > >::value >::type
Return the held element values as a range of complex APInts.
template<typename T >
using APFloatValueTemplateCheckT = typename std::enable_if< std::is_same< T, APFloat >::value >::type
Return the held element values as a range of APFloat.
template<typename T >
using ComplexAPFloatValueTemplateCheckT = typename std::enable_if< std::is_same< T, std::complex< APFloat > >::value >::type
Return the held element values as a range of complex APFloat.
Public Types inherited from mlir::Attribute
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using AttrBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::AttributeUniquer, Traits... >
Utility class for implementing attributes.
using ImplType = AttributeStorage
using ValueType = void
using AbstractTy = AbstractAttribute
Public Member Functions
operator ElementsAttr () const
Allow implicit conversion to ElementsAttr.
bool isSplat () const
Returns true if this attribute corresponds to a splat, i.e.
Attribute getSplatValue () const
Return the splat value for this attribute.
template<typename T >
std::enable_if<!std::is_base_of< Attribute, T >::value||std::is_same< Attribute, T >::value, T >::type getSplatValue () const
template<typename T >
std::enable_if< std::is_base_of< Attribute, T >::value &&!std::is_same< Attribute, T >::value, T >::type getSplatValue () const
Return the splat value for derived attribute element types.
Attribute getValue (ArrayRef< uint64_t > index) const
Return the value at the given index.
template<typename T >
T getValue (ArrayRef< uint64_t > index) const
template<typename T >
T getFlatValue (uint64_t index) const
Return the value at the given flattened index.
template<typename T , typename = IntFloatValueTemplateCheckT<T>>
llvm::iterator_range< ElementIterator< T > > getValues () const
template<typename T , typename = IntFloatValueTemplateCheckT<T>>
ElementIterator< T > value_begin () const
template<typename T , typename = IntFloatValueTemplateCheckT<T>>
ElementIterator< T > value_end () const
template<typename T , typename ElementT = typename T::value_type, typename = ComplexValueTemplateCheckT<T, ElementT>>
llvm::iterator_range< ElementIterator< T > > getValues () const
template<typename T , typename ElementT = typename T::value_type, typename = ComplexValueTemplateCheckT<T, ElementT>>
ElementIterator< T > value_begin () const
template<typename T , typename ElementT = typename T::value_type, typename = ComplexValueTemplateCheckT<T, ElementT>>
ElementIterator< T > value_end () const
template<typename T , typename = StringRefValueTemplateCheckT<T>>
llvm::iterator_range< ElementIterator< StringRef > > getValues () const
template<typename T , typename = StringRefValueTemplateCheckT<T>>
ElementIterator< StringRef > value_begin () const
template<typename T , typename = StringRefValueTemplateCheckT<T>>
ElementIterator< StringRef > value_end () const
template<typename T , typename = AttributeValueTemplateCheckT<T>>
llvm::iterator_range< AttributeElementIterator > getValues () const
template<typename T , typename = AttributeValueTemplateCheckT<T>>
AttributeElementIterator value_begin () const
template<typename T , typename = AttributeValueTemplateCheckT<T>>
AttributeElementIterator value_end () const
template<typename T , typename = DerivedAttrValueTemplateCheckT<T>>
llvm::iterator_range< DerivedAttributeElementIterator< T > > getValues () const
template<typename T , typename = DerivedAttrValueTemplateCheckT<T>>
DerivedAttributeElementIterator< T > value_begin () const
template<typename T , typename = DerivedAttrValueTemplateCheckT<T>>
DerivedAttributeElementIterator< T > value_end () const
template<typename T , typename = BoolValueTemplateCheckT<T>>
llvm::iterator_range< BoolElementIterator > getValues () const
template<typename T , typename = BoolValueTemplateCheckT<T>>
BoolElementIterator value_begin () const
template<typename T , typename = BoolValueTemplateCheckT<T>>
BoolElementIterator value_end () const
template<typename T , typename = APIntValueTemplateCheckT<T>>
llvm::iterator_range< IntElementIterator > getValues () const
template<typename T , typename = APIntValueTemplateCheckT<T>>
IntElementIterator value_begin () const
template<typename T , typename = APIntValueTemplateCheckT<T>>
IntElementIterator value_end () const
template<typename T , typename = ComplexAPIntValueTemplateCheckT<T>>
llvm::iterator_range< ComplexIntElementIterator > getValues () const
template<typename T , typename = ComplexAPIntValueTemplateCheckT<T>>
ComplexIntElementIterator value_begin () const
template<typename T , typename = ComplexAPIntValueTemplateCheckT<T>>
ComplexIntElementIterator value_end () const
template<typename T , typename = APFloatValueTemplateCheckT<T>>
llvm::iterator_range< FloatElementIterator > getValues () const
template<typename T , typename = APFloatValueTemplateCheckT<T>>
FloatElementIterator value_begin () const
template<typename T , typename = APFloatValueTemplateCheckT<T>>
FloatElementIterator value_end () const
template<typename T , typename = ComplexAPFloatValueTemplateCheckT<T>>
llvm::iterator_range< ComplexFloatElementIterator > getValues () const
template<typename T , typename = ComplexAPFloatValueTemplateCheckT<T>>
ComplexFloatElementIterator value_begin () const
template<typename T , typename = ComplexAPFloatValueTemplateCheckT<T>>
ComplexFloatElementIterator value_end () const
ArrayRef< char > getRawData () const
Return the raw storage data held by this attribute.
ArrayRef< StringRef > getRawStringData () const
Return the raw StringRef data held by this attribute.
ShapedType getType () const
Return the type of this ElementsAttr, guaranteed to be a vector or tensor with static shape.
Type getElementType () const
Return the element type of this DenseElementsAttr.
int64_t getNumElements () const
Returns the number of elements held by this attribute.
int64_t size () const
Returns the number of elements held by this attribute.
bool empty () const
Returns if the number of elements held by this attribute is 0.
DenseElementsAttr reshape (ShapedType newType)
Return a new DenseElementsAttr that has the same data as the current attribute, but has been reshaped to 'newType'.
DenseElementsAttr bitcast (Type newElType)
Return a new DenseElementsAttr that has the same data as the current attribute, but has bitcast elements to 'newElType'.
DenseElementsAttr mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new DenseElementsAttr by mapping each int value to a new underlying APInt.
DenseElementsAttr mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new DenseElementsAttr by mapping each float value to a new underlying APInt.
Public Member Functions inherited from mlir::Attribute
constexpr Attribute ()
Attribute (const ImplType *impl)
Attribute (const Attribute &other)=default
Attribute & operator= (const Attribute &other)=default
bool operator== (Attribute other) const
bool operator!= (Attribute other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete attribute type.
Type getType () const
Return the type of this attribute.
MLIRContext * getContext () const
Return the context this attribute belongs to.
Dialect & getDialect () const
Get the dialect this attribute is registered to.
void print (raw_ostream &os) const
Print the attribute.
void dump () const
const void * getAsOpaquePointer () const
Get an opaque pointer to the attribute.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the type was registered with a particular trait.
const AbstractTy & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Static Public Member Functions
static bool classof (Attribute attr)
Method for support type inquiry through isa, cast and dyn_cast.
static DenseElementsAttr get (ShapedType type, ArrayRef< Attribute > values)
Constructs a dense elements attribute from an array of element values.
template<typename T , typename = typename std::enable_if< std::numeric_limits<T>::is_integer || is_valid_cpp_fp_type<T>::value>::type>
static DenseElementsAttr get (const ShapedType &type, ArrayRef< T > values)
Constructs a dense integer elements attribute from an array of integer or floating-point values.
template<typename T , typename = typename std::enable_if< std::numeric_limits<T>::is_integer || is_valid_cpp_fp_type<T>::value || detail::is_complex_t<T>::value>::type>
static DenseElementsAttr get (const ShapedType &type, T value)
Constructs a dense integer elements attribute from a single element.
template<typename T , typename ElementT = typename T::value_type, typename = typename std::enable_if< detail::is_complex_t<T>::value && (std::numeric_limits<ElementT>::is_integer || is_valid_cpp_fp_type<ElementT>::value)>::type>
static DenseElementsAttr get (const ShapedType &type, ArrayRef< T > values)
Constructs a dense complex elements attribute from an array of complex values.
static DenseElementsAttr get (ShapedType type, ArrayRef< bool > values)
Overload of the above 'get' method that is specialized for boolean values.
static DenseElementsAttr get (ShapedType type, ArrayRef< StringRef > values)
Overload of the above 'get' method that is specialized for StringRef values.
static DenseElementsAttr get (ShapedType type, ArrayRef< APInt > values)
Constructs a dense integer elements attribute from an array of APInt values.
static DenseElementsAttr get (ShapedType type, ArrayRef< std::complex< APInt >> values)
Constructs a dense complex elements attribute from an array of APInt values.
static DenseElementsAttr get (ShapedType type, ArrayRef< APFloat > values)
Constructs a dense float elements attribute from an array of APFloat values.
static DenseElementsAttr get (ShapedType type, ArrayRef< std::complex< APFloat >> values)
Constructs a dense complex elements attribute from an array of APFloat values.
template<typename T >
static DenseElementsAttr get (const ShapedType &type, const std::initializer_list< T > &list)
Construct a dense elements attribute for an initializer_list of values.
static DenseElementsAttr getFromRawBuffer (ShapedType type, ArrayRef< char > rawBuffer, bool isSplatBuffer)
Construct a dense elements attribute from a raw buffer representing the data for this attribute.
static bool isValidRawBuffer (ShapedType type, ArrayRef< char > rawBuffer, bool &detectedSplat)
Returns true if the given buffer is a valid raw buffer for the given type.
Static Public Member Functions inherited from mlir::Attribute
static bool classof (Attribute)
static Attribute getFromOpaquePointer (const void *ptr)
Construct an attribute from the opaque pointer representation.
Protected Member Functions
IntElementIterator raw_int_begin () const
Iterators to various elements that require out-of-line definition.
IntElementIterator raw_int_end () const
llvm::iterator_range< ComplexIntElementIterator > getComplexIntValues () const
ComplexIntElementIterator complex_value_begin () const
ComplexIntElementIterator complex_value_end () const
llvm::iterator_range< FloatElementIterator > getFloatValues () const
Return the held element values as a range of APFloat.
FloatElementIterator float_value_begin () const
FloatElementIterator float_value_end () const
llvm::iterator_range< ComplexFloatElementIterator > getComplexFloatValues () const
ComplexFloatElementIterator complex_float_value_begin () const
ComplexFloatElementIterator complex_float_value_end () const
bool isValidBool () const
Check the information for a C++ data type, check if this type is valid for the current attribute.
bool isValidIntOrFloat (int64_t dataEltSize, bool isInt, bool isSigned) const
bool isValidComplex (int64_t dataEltSize, bool isInt, bool isSigned) const
Static Protected Member Functions
static DenseElementsAttr getRawComplex (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned)
Overload of the raw 'get' method that asserts that the given type is of complex type.
static DenseElementsAttr getRawIntOrFloat (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned)
Overload of the raw 'get' method that asserts that the given type is of integer or floating-point type.
Additional Inherited Members
Protected Attributes inherited from mlir::Attribute
ImplType * impl
Detailed Description
An attribute that represents a reference to a dense vector or tensor object.
Definition at line 72 of file BuiltinAttributes.h.
Member Typedef Documentation
APFloatValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::APFloatValueTemplateCheckT = typename std::enable_if<std::is_same<T, APFloat>::value>::type
Return the held element values as a range of APFloat.
The element type of this attribute must be of float type.
Definition at line 570 of file BuiltinAttributes.h.
APIntValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::APIntValueTemplateCheckT = typename std::enable_if<std::is_same<T, APInt>::value>::type
Return the held element values as a range of APInts.
The element type of this attribute must be of integer type.
Definition at line 531 of file BuiltinAttributes.h.
AttributeValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::AttributeValueTemplateCheckT = typename std::enable_if<std::is_same<T, Attribute>::value>::type
Return the held element values as a range of Attributes.
Definition at line 465 of file BuiltinAttributes.h.
BoolValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::BoolValueTemplateCheckT = typename std::enable_if<std::is_same<T, bool>::value>::type
Return the held element values as a range of bool.
The element type of this attribute must be of integer type of bitwidth 1.
Definition at line 509 of file BuiltinAttributes.h.
ComplexAPFloatValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::ComplexAPFloatValueTemplateCheckT = typename std::enable_if< std::is_same<T, std::complex<APFloat> >::value>::type
Return the held element values as a range of complex APFloat.
The element type of this attribute must be a complex of float type.
Definition at line 588 of file BuiltinAttributes.h.
ComplexAPIntValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::ComplexAPIntValueTemplateCheckT = typename std::enable_if< std::is_same<T, std::complex<APInt> >::value>::type
Return the held element values as a range of complex APInts.
The element type of this attribute must be a complex of integer type.
Definition at line 552 of file BuiltinAttributes.h.
ComplexValueTemplateCheckT
template<typename T , typename ElementT > using mlir::DenseElementsAttr::ComplexValueTemplateCheckT = typename std::enable_if<detail::is_complex_t<T>::value && (std::numeric_limits<ElementT>::is_integer || is_valid_cpp_fp_type<ElementT>::value)>::type
Return the held element values as a range of std::complex.
Definition at line 413 of file BuiltinAttributes.h.
DerivedAttributeElementIterator
template<typename T > using mlir::DenseElementsAttr::DerivedAttributeElementIterator = llvm::mapped_iterator<AttributeElementIterator, T (*)(Attribute)>
Definition at line 487 of file BuiltinAttributes.h.
DerivedAttrValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::DerivedAttrValueTemplateCheckT = typename std::enable_if<std::is_base_of<Attribute, T>::value && !std::is_same<Attribute, T>::value>::type
Return the held element values a range of T, where T is a derived attribute type.
Definition at line 484 of file BuiltinAttributes.h.
IntFloatValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::IntFloatValueTemplateCheckT = typename std::enable_if<(!std::is_same<T, bool>::value && std::numeric_limits<T>::is_integer) || is_valid_cpp_fp_type<T>::value>::type
Return the held element values as a range of integer or floating-point values.
Definition at line 385 of file BuiltinAttributes.h.
StringRefValueTemplateCheckT
template<typename T > using mlir::DenseElementsAttr::StringRefValueTemplateCheckT = typename std::enable_if<std::is_same<T, StringRef>::value>::type
Return the held element values as a range of StringRef.
Definition at line 442 of file BuiltinAttributes.h.
Member Function Documentation
bitcast()
DenseElementsAttr DenseElementsAttr::bitcast (Type newElType)
Return a new DenseElementsAttr that has the same data as the current attribute, but has bitcast elements to 'newElType'.
Return a new DenseElementsAttr that has the same data as the current attribute, but has bitcast elements such that it is now 'newType'.
The new type must have the same bitwidth as the current element type.
The new type must have the same shape and element types of the same bitwidth as the current type.
Definition at line 967 of file BuiltinAttributes.cpp.
References mlir::ShapedType::clone(), mlir::detail::getDenseElementBitWidth(), and mlir::ShapedType::getElementType().
classof()
bool DenseElementsAttr::classof (Attribute attr) static
Method for support type inquiry through isa, cast and dyn_cast.
Definition at line 666 of file BuiltinAttributes.cpp.
References mlir::Attribute::isa().
complex_float_value_begin()
auto DenseElementsAttr::complex_float_value_begin () const protected
Definition at line 925 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), getElementType(), and mlir::Type::isa().
complex_float_value_end()
auto DenseElementsAttr::complex_float_value_end () const protected
Definition at line 931 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), getElementType(), and mlir::Type::isa().
complex_value_begin()
auto DenseElementsAttr::complex_value_begin () const protected
Definition at line 887 of file BuiltinAttributes.cpp.
References getElementType(), and isComplexOfIntType().
complex_value_end()
auto DenseElementsAttr::complex_value_end () const protected
Definition at line 893 of file BuiltinAttributes.cpp.
References getElementType(), and isComplexOfIntType().
empty()
bool mlir::DenseElementsAttr::empty () const inline
Returns if the number of elements held by this attribute is 0.
Definition at line 624 of file BuiltinAttributes.h.
float_value_begin()
auto DenseElementsAttr::float_value_begin () const protected
Definition at line 908 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), elementType(), and getElementType().
float_value_end()
auto DenseElementsAttr::float_value_end () const protected
Definition at line 912 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), elementType(), and getElementType().
get() [1/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< Attribute > values) static
Constructs a dense elements attribute from an array of element values.
Each element attribute value is expected to be an element of 'type'. 'type' must be a vector or tensor with static shape. If the element of type is non-integer/index/float it is assumed to be a string type.
Definition at line 670 of file BuiltinAttributes.cpp.
References mlir::Attribute::cast(), mlir::detail::getDenseElementBitWidth(), getDenseElementStorageWidth(), mlir::ShapedType::getElementType(), hasSameElementsOrSplat(), mlir::Attribute::isa(), mlir::Type::isIntOrIndexOrFloat(), and writeBits().
Referenced by mlir::spirv::Deserializer::collect(), convertStructType(), createConstantAllBitsSet(), createFPConstant(), createInitialVector(), diag(), foldExtractStridedOpFromInsertChain(), foldTransferInBoundsAttribute(), mlir::DenseFPElementsAttr::get(), mlir::DenseIntElementsAttr::get(), getDenseAttribute(), mlir::Builder::getZeroAttr(), isBoolScalarOrVector(), ConstantTransposeOptimization::matchAndRewrite(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), parseElementAttrHexValues(), mlir::detail::Parser::parseSparseElementsAttr(), replaceTransferOpWithMubuf(), vectorizeConstant(), and verify().
get() [2/11]
template<typename T , typename = typename std::enable_if< std::numeric_limits<T>::is_integer || is_valid_cpp_fp_type<T>::value>::type> static DenseElementsAttr mlir::DenseElementsAttr::get (const ShapedType & type, ArrayRef< T > values) inline static
Constructs a dense integer elements attribute from an array of integer or floating-point values.
Each value is expected to be the same bitwidth of the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 112 of file BuiltinAttributes.h.
get() [3/11]
template<typename T , typename = typename std::enable_if< std::numeric_limits<T>::is_integer || is_valid_cpp_fp_type<T>::value || detail::is_complex_t<T>::value>::type> static DenseElementsAttr mlir::DenseElementsAttr::get (const ShapedType & type, T value) inline static
Constructs a dense integer elements attribute from a single element.
Definition at line 124 of file BuiltinAttributes.h.
References value.
get() [4/11]
template<typename T , typename ElementT = typename T::value_type, typename = typename std::enable_if< detail::is_complex_t<T>::value && (std::numeric_limits<ElementT>::is_integer || is_valid_cpp_fp_type<ElementT>::value)>::type> static DenseElementsAttr mlir::DenseElementsAttr::get (const ShapedType & type, ArrayRef< T > values) inline static
Constructs a dense complex elements attribute from an array of complex values.
Each value is expected to be the same bitwidth of the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 136 of file BuiltinAttributes.h.
get() [5/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< bool > values) static
Overload of the above 'get' method that is specialized for boolean values.
Definition at line 714 of file BuiltinAttributes.cpp.
References mlir::ShapedType::getElementType(), hasSameElementsOrSplat(), mlir::Type::isInteger(), and setBit().
get() [6/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< StringRef > values) static
Overload of the above 'get' method that is specialized for StringRef values.
Definition at line 726 of file BuiltinAttributes.cpp.
References mlir::ShapedType::getElementType(), and mlir::Type::isIntOrFloat().
get() [7/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< APInt > values) static
Constructs a dense integer elements attribute from an array of APInt values.
Each APInt value is expected to have the same bitwidth as the element type of 'type'. 'type' must be a vector or tensor with static shape.
Each APInt value is expected to have the same bitwidth as the element type of 'type'.
Definition at line 735 of file BuiltinAttributes.cpp.
References getDenseElementStorageWidth(), mlir::ShapedType::getElementType(), hasSameElementsOrSplat(), and mlir::Type::isIntOrIndex().
get() [8/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< std::complex< APInt >> values) static
Constructs a dense complex elements attribute from an array of APInt values.
Each APInt value is expected to have the same bitwidth as the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 743 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), getDenseElementStorageWidth(), mlir::ShapedType::getElementType(), and hasSameElementsOrSplat().
get() [9/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< APFloat > values) static
Constructs a dense float elements attribute from an array of APFloat values.
Each APFloat value is expected to have the same bitwidth as the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 758 of file BuiltinAttributes.cpp.
References getDenseElementStorageWidth(), mlir::ShapedType::getElementType(), hasSameElementsOrSplat(), and mlir::Type::isa().
get() [10/11]
DenseElementsAttr DenseElementsAttr::get (ShapedType type, ArrayRef< std::complex< APFloat >> values) static
Constructs a dense complex elements attribute from an array of APFloat values.
Each APFloat value is expected to have the same bitwidth as the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 767 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), getDenseElementStorageWidth(), mlir::ShapedType::getElementType(), and hasSameElementsOrSplat().
get() [11/11]
template<typename T > static DenseElementsAttr mlir::DenseElementsAttr::get (const ShapedType & type, const std::initializer_list< T > & list) inline static
Construct a dense elements attribute for an initializer_list of values.
Each value is expected to be the same bitwidth of the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 180 of file BuiltinAttributes.h.
getComplexFloatValues()
auto DenseElementsAttr::getComplexFloatValues () const protected
Definition at line 917 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), getElementType(), and mlir::Type::isa().
getComplexIntValues()
auto DenseElementsAttr::getComplexIntValues () const protected
Definition at line 880 of file BuiltinAttributes.cpp.
References getElementType(), and isComplexOfIntType().
getElementType()
Type DenseElementsAttr::getElementType () const
Return the element type of this DenseElementsAttr.
Definition at line 995 of file BuiltinAttributes.cpp.
Referenced by mlir::DenseElementsAttr::BoolElementIterator::operator*(), and mlir::DenseElementsAttr::IntElementIterator::operator*().
getFlatValue()
template<typename T > T mlir::DenseElementsAttr::getFlatValue (uint64_t index) const inline
Return the value at the given flattened index.
Definition at line 375 of file BuiltinAttributes.h.
References value.
getFloatValues()
auto DenseElementsAttr::getFloatValues () const protected
Return the held element values as a range of APFloat.
The element type of this attribute must be of float type.
Definition at line 901 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), elementType(), and getElementType().
getFromRawBuffer()
DenseElementsAttr DenseElementsAttr::getFromRawBuffer (ShapedType type, ArrayRef< char > rawBuffer, bool isSplatBuffer) static
Construct a dense elements attribute from a raw buffer representing the data for this attribute.
Users are encouraged to use one of the constructors above, which provide more safeties. However, this constructor is useful for tools which may want to interop and can follow the precise definition.
The format of the raw buffer is a densely packed array of values that can be bitcast to the storage format of the element type specified. Types that are not byte aligned will be:
For bitwidth > 1: Rounded up to the next byte.
For bitwidth = 1: Packed into 8bit bytes with bits corresponding to the linear order of the shape type from MSB to LSB, padded to on the right.
If isSplatBuffer is true, then the raw buffer should contain a single element (or for the case of 1-bit, a single byte of 0 or 255), which will be used to construct a splat.
Users should generally not use this methods as the expected buffer format may not be a form the user expects.
Definition at line 782 of file BuiltinAttributes.cpp.
Referenced by mlirDenseElementsAttrRawBufferGet(), parseElementAttrHexValues(), and verify().
getNumElements()
int64_t DenseElementsAttr::getNumElements () const
Returns the number of elements held by this attribute.
Definition at line 999 of file BuiltinAttributes.cpp.
Referenced by convertDenseElementsAttr().
getRawComplex()
DenseElementsAttr DenseElementsAttr::getRawComplex (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned) static protected
Overload of the raw 'get' method that asserts that the given type is of complex type.
Defaults down the subclass implementation.
This method is used to verify type invariants that the templatized 'get' method cannot.
Definition at line 842 of file BuiltinAttributes.cpp.
getRawData()
ArrayRef< char > DenseElementsAttr::getRawData () const
Return the raw storage data held by this attribute.
Users should generally not use this directly, as the internal storage format is not always in the form the user might expect.
Definition at line 940 of file BuiltinAttributes.cpp.
Referenced by convertDenseElementsAttr(), mlir::DenseElementsAttr::AttributeElementIterator::operator*(), mlir::DenseElementsAttr::BoolElementIterator::operator*(), mlir::DenseElementsAttr::IntElementIterator::operator*(), and verify().
getRawIntOrFloat()
DenseElementsAttr DenseElementsAttr::getRawIntOrFloat (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned) static protected
Overload of the raw 'get' method that asserts that the given type is of integer or floating-point type.
This method is used to verify type invariants that the templatized 'get' method cannot.
Definition at line 849 of file BuiltinAttributes.cpp.
getRawStringData()
ArrayRef< StringRef > DenseElementsAttr::getRawStringData () const
Return the raw StringRef data held by this attribute.
Definition at line 944 of file BuiltinAttributes.cpp.
getSplatValue() [1/3]
Attribute mlir::DenseElementsAttr::getSplatValue () const inline
Return the splat value for this attribute.
This asserts that the attribute corresponds to a splat.
Definition at line 346 of file BuiltinAttributes.h.
References value.
Referenced by convertDenseElementsAttr(), and fuseWithReshapeByExpansion().
getSplatValue() [2/3]
template<typename T > std::enable_if<!std::is_base_of<Attribute, T>::value || std::is_same<Attribute, T>::value, T>::type mlir::DenseElementsAttr::getSplatValue () const inline
Definition at line 351 of file BuiltinAttributes.h.
References value.
getSplatValue() [3/3]
template<typename T > std::enable_if<std::is_base_of<Attribute, T>::value && !std::is_same<Attribute, T>::value, T>::type mlir::DenseElementsAttr::getSplatValue () const inline
Return the splat value for derived attribute element types.
Definition at line 360 of file BuiltinAttributes.h.
getType()
ShapedType DenseElementsAttr::getType () const
Return the type of this ElementsAttr, guaranteed to be a vector or tensor with static shape.
Definition at line 991 of file BuiltinAttributes.cpp.
References mlir::Type::cast(), and mlir::Attribute::getType().
Referenced by mlir::DenseIntElementsAttr::classof(), convertDenseElementsAttr(), and fuseWithReshapeByExpansion().
getValue() [1/2]
Attribute mlir::DenseElementsAttr::getValue (ArrayRef< uint64_t > index) const inline
Return the value at the given index.
The 'index' is expected to refer to a valid element.
Definition at line 366 of file BuiltinAttributes.h.
Referenced by ConstantTransposeOptimization::matchAndRewrite(), and parseElementAttrHexValues().
getValue() [2/2]
template<typename T > T mlir::DenseElementsAttr::getValue (ArrayRef< uint64_t > index) const inline
Definition at line 370 of file BuiltinAttributes.h.
getValues() [1/10]
template<typename T , typename = IntFloatValueTemplateCheckT<T>> llvm::iterator_range<ElementIterator<T> > mlir::DenseElementsAttr::getValues () const inline
Definition at line 387 of file BuiltinAttributes.h.
References isValidIntOrFloat().
Referenced by convertSparseElementsAttr(), and executeGetOperandsResults().
getValues() [2/10]
template<typename T , typename ElementT = typename T::value_type, typename = ComplexValueTemplateCheckT<T, ElementT>> llvm::iterator_range<ElementIterator<T> > mlir::DenseElementsAttr::getValues () const inline
Definition at line 416 of file BuiltinAttributes.h.
getValues() [3/10]
template<typename T , typename = StringRefValueTemplateCheckT<T>> llvm::iterator_range<ElementIterator<StringRef> > mlir::DenseElementsAttr::getValues () const inline
Definition at line 444 of file BuiltinAttributes.h.
getValues() [4/10]
template<typename T , typename = AttributeValueTemplateCheckT<T>> llvm::iterator_range<AttributeElementIterator> mlir::DenseElementsAttr::getValues () const inline
Definition at line 467 of file BuiltinAttributes.h.
getValues() [5/10]
template<typename T , typename = DerivedAttrValueTemplateCheckT<T>> llvm::iterator_range<DerivedAttributeElementIterator<T> > mlir::DenseElementsAttr::getValues () const inline
Definition at line 489 of file BuiltinAttributes.h.
getValues() [6/10]
template<typename T , typename = BoolValueTemplateCheckT<T>> llvm::iterator_range<BoolElementIterator> mlir::DenseElementsAttr::getValues () const inline
Definition at line 511 of file BuiltinAttributes.h.
getValues() [7/10]
template<typename T , typename = APIntValueTemplateCheckT<T>> llvm::iterator_range<IntElementIterator> mlir::DenseElementsAttr::getValues () const inline
Definition at line 533 of file BuiltinAttributes.h.
References getElementType().
getValues() [8/10]
template<typename T , typename = ComplexAPIntValueTemplateCheckT<T>> llvm::iterator_range<ComplexIntElementIterator> mlir::DenseElementsAttr::getValues () const inline
Definition at line 554 of file BuiltinAttributes.h.
getValues() [9/10]
template<typename T , typename = APFloatValueTemplateCheckT<T>> llvm::iterator_range<FloatElementIterator> mlir::DenseElementsAttr::getValues () const inline
Definition at line 572 of file BuiltinAttributes.h.
getValues() [10/10]
template<typename T , typename = ComplexAPFloatValueTemplateCheckT<T>> llvm::iterator_range<ComplexFloatElementIterator> mlir::DenseElementsAttr::getValues () const inline
Definition at line 590 of file BuiltinAttributes.h.
isSplat()
bool DenseElementsAttr::isSplat () const
Returns true if this attribute corresponds to a splat, i.e.
if all element values are the same.
Definition at line 871 of file BuiltinAttributes.cpp.
Referenced by mlir::SplatElementsAttr::classof(), convertDenseElementsAttr(), fuseWithReshapeByExpansion(), ReshapeConstOptimization::matchAndRewrite(), mlir::DenseElementsAttr::AttributeElementIterator::operator*(), mlir::DenseElementsAttr::BoolElementIterator::operator*(), mlir::DenseElementsAttr::IntElementIterator::operator*(), and verify().
isValidBool()
bool mlir::DenseElementsAttr::isValidBool () const inline protected
Check the information for a C++ data type, check if this type is valid for the current attribute.
This method is used to verify specific type invariants that the templatized 'getValues' method cannot.
Definition at line 692 of file BuiltinAttributes.h.
References getElementType(), and isValidIntOrFloat().
isValidComplex()
bool DenseElementsAttr::isValidComplex (int64_t dataEltSize, bool isInt, bool isSigned) const protected
Definition at line 862 of file BuiltinAttributes.cpp.
References getElementType(), and isValidIntOrFloat().
isValidIntOrFloat()
bool DenseElementsAttr::isValidIntOrFloat (int64_t dataEltSize, bool isInt, bool isSigned) const protected
Definition at line 858 of file BuiltinAttributes.cpp.
References getElementType(), and isValidIntOrFloat().
isValidRawBuffer()
bool DenseElementsAttr::isValidRawBuffer (ShapedType type, ArrayRef< char > rawBuffer, bool & detectedSplat) static
Returns true if the given buffer is a valid raw buffer for the given type.
detectedSplat is set if the buffer is valid and represents a splat buffer. The definition may be expanded over time, but currently, a splat buffer is detected if:
For >1bit: The buffer consists of a single element.
For 1bit: The buffer consists of a single byte with value 0 or 255.
User code should be prepared for additional, conformant patterns to be identified as splats in the future.
Definition at line 789 of file BuiltinAttributes.cpp.
References getDenseElementStorageWidth(), mlir::ShapedType::getElementType(), and mlir::ShapedType::getNumElements().
Referenced by mlirDenseElementsAttrRawBufferGet(), and parseElementAttrHexValues().
mapValues() [1/2]
DenseElementsAttr DenseElementsAttr::mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new DenseElementsAttr by mapping each int value to a new underlying APInt.
The new values can represent either an integer or float. This underlying type must be an DenseIntElementsAttr.
Definition at line 981 of file BuiltinAttributes.cpp.
mapValues() [2/2]
DenseElementsAttr DenseElementsAttr::mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new DenseElementsAttr by mapping each float value to a new underlying APInt.
the new values can represent either an integer or float. This underlying type must be an DenseFPElementsAttr.
Definition at line 986 of file BuiltinAttributes.cpp.
operator ElementsAttr()
mlir::DenseElementsAttr::operator ElementsAttr () const inline
Allow implicit conversion to ElementsAttr.
Definition at line 77 of file BuiltinAttributes.h.
raw_int_begin()
IntElementIterator mlir::DenseElementsAttr::raw_int_begin () const inline protected
Iterators to various elements that require out-of-line definition.
These are hidden from the user to encourage consistent use of the getValues/value_begin/value_end API.
Definition at line 657 of file BuiltinAttributes.h.
raw_int_end()
IntElementIterator mlir::DenseElementsAttr::raw_int_end () const inline protected
Definition at line 660 of file BuiltinAttributes.h.
reshape()
DenseElementsAttr DenseElementsAttr::reshape (ShapedType newType)
Return a new DenseElementsAttr that has the same data as the current attribute, but has been reshaped to 'newType'.
The new type must have the same total number of elements as well as element type.
Definition at line 951 of file BuiltinAttributes.cpp.
References mlir::ShapedType::getElementType(), and mlir::ShapedType::getNumElements().
Referenced by ReshapeConstOptimization::matchAndRewrite().
size()
int64_t mlir::DenseElementsAttr::size () const inline
Returns the number of elements held by this attribute.
Definition at line 621 of file BuiltinAttributes.h.
value_begin() [1/10]
template<typename T , typename = IntFloatValueTemplateCheckT<T>> ElementIterator<T> mlir::DenseElementsAttr::value_begin () const inline
Definition at line 396 of file BuiltinAttributes.h.
References isValidIntOrFloat().
value_begin() [2/10]
template<typename T , typename ElementT = typename T::value_type, typename = ComplexValueTemplateCheckT<T, ElementT>> ElementIterator<T> mlir::DenseElementsAttr::value_begin () const inline
Definition at line 426 of file BuiltinAttributes.h.
value_begin() [3/10]
template<typename T , typename = StringRefValueTemplateCheckT<T>> ElementIterator<StringRef> mlir::DenseElementsAttr::value_begin () const inline
Definition at line 452 of file BuiltinAttributes.h.
value_begin() [4/10]
template<typename T , typename = AttributeValueTemplateCheckT<T>> AttributeElementIterator mlir::DenseElementsAttr::value_begin () const inline
Definition at line 471 of file BuiltinAttributes.h.
value_begin() [5/10]
template<typename T , typename = DerivedAttrValueTemplateCheckT<T>> DerivedAttributeElementIterator<T> mlir::DenseElementsAttr::value_begin () const inline
Definition at line 495 of file BuiltinAttributes.h.
value_begin() [6/10]
template<typename T , typename = BoolValueTemplateCheckT<T>> BoolElementIterator mlir::DenseElementsAttr::value_begin () const inline
Definition at line 517 of file BuiltinAttributes.h.
value_begin() [7/10]
template<typename T , typename = APIntValueTemplateCheckT<T>> IntElementIterator mlir::DenseElementsAttr::value_begin () const inline
Definition at line 538 of file BuiltinAttributes.h.
References getElementType().
value_begin() [8/10]
template<typename T , typename = ComplexAPIntValueTemplateCheckT<T>> ComplexIntElementIterator mlir::DenseElementsAttr::value_begin () const inline
Definition at line 558 of file BuiltinAttributes.h.
value_begin() [9/10]
template<typename T , typename = APFloatValueTemplateCheckT<T>> FloatElementIterator mlir::DenseElementsAttr::value_begin () const inline
Definition at line 576 of file BuiltinAttributes.h.
value_begin() [10/10]
template<typename T , typename = ComplexAPFloatValueTemplateCheckT<T>> ComplexFloatElementIterator mlir::DenseElementsAttr::value_begin () const inline
Definition at line 594 of file BuiltinAttributes.h.
value_end() [1/10]
template<typename T , typename = IntFloatValueTemplateCheckT<T>> ElementIterator<T> mlir::DenseElementsAttr::value_end () const inline
Definition at line 402 of file BuiltinAttributes.h.
References isValidIntOrFloat(), and value.
value_end() [2/10]
template<typename T , typename ElementT = typename T::value_type, typename = ComplexValueTemplateCheckT<T, ElementT>> ElementIterator<T> mlir::DenseElementsAttr::value_end () const inline
Definition at line 433 of file BuiltinAttributes.h.
value_end() [3/10]
template<typename T , typename = StringRefValueTemplateCheckT<T>> ElementIterator<StringRef> mlir::DenseElementsAttr::value_end () const inline
Definition at line 457 of file BuiltinAttributes.h.
value_end() [4/10]
template<typename T , typename = AttributeValueTemplateCheckT<T>> AttributeElementIterator mlir::DenseElementsAttr::value_end () const inline
Definition at line 475 of file BuiltinAttributes.h.
References value.
value_end() [5/10]
template<typename T , typename = DerivedAttrValueTemplateCheckT<T>> DerivedAttributeElementIterator<T> mlir::DenseElementsAttr::value_end () const inline
Definition at line 500 of file BuiltinAttributes.h.
value_end() [6/10]
template<typename T , typename = BoolValueTemplateCheckT<T>> BoolElementIterator mlir::DenseElementsAttr::value_end () const inline
Definition at line 522 of file BuiltinAttributes.h.
value_end() [7/10]
template<typename T , typename = APIntValueTemplateCheckT<T>> IntElementIterator mlir::DenseElementsAttr::value_end () const inline
Definition at line 543 of file BuiltinAttributes.h.
References getElementType().
value_end() [8/10]
template<typename T , typename = ComplexAPIntValueTemplateCheckT<T>> ComplexIntElementIterator mlir::DenseElementsAttr::value_end () const inline
Definition at line 562 of file BuiltinAttributes.h.
value_end() [9/10]
template<typename T , typename = APFloatValueTemplateCheckT<T>> FloatElementIterator mlir::DenseElementsAttr::value_end () const inline
Definition at line 580 of file BuiltinAttributes.h.
value_end() [10/10]
template<typename T , typename = ComplexAPFloatValueTemplateCheckT<T>> ComplexFloatElementIterator mlir::DenseElementsAttr::value_end () const inline
Definition at line 598 of file BuiltinAttributes.h.
References getElementType().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinAttributes.h
lib/IR/BuiltinAttributes.cpp