MLIR: lib/Dialect/Linalg/Transforms/ComprehensiveBufferize.cpp File Reference
ComprehensiveBufferize.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/ComprehensiveBufferize.h"
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/BufferUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "comprehensive-module-bufferize"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X)
Typedefs
using BufferRelation = BufferizationAliasInfo::BufferRelation
Enumerations
enum InPlaceSpec { InPlaceSpec::False, InPlaceSpec::True, InPlaceSpec::None }
Functions
static std::string printOperationInfo (Operation *op, bool prefix)
Print the operation name and bufferization information.
static std::string printValueInfo (Value value, bool prefix)
Print the bufferization information for the defining op or block argument.
static bool isaTensor (Type t)
static FuncOp getCalledFunction (CallOpInterface callOp)
Return the FuncOp called by callOp.
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static bool isInitTensorOp (Value value)
Return true if value is the result of an InitTensorOp or a cast thereof.
static void map (BlockAndValueMapping &bvm, ValueRange keys, ValueRange values)
Wrapper for better debugging.
static void map (BlockAndValueMapping &bvm, Value key, Value value)
Wrapper for better debugging.
static Value lookup (const BlockAndValueMapping &bvm, Value key)
Wrapper for better debugging.
static StringRef stringify (InPlaceSpec val)
static Optional< InPlaceSpec > symbolize (StringRef str)
static void setInPlaceOpResult (OpResult opResult, InPlaceSpec inPlace=InPlaceSpec::True)
Mark whether OpResult can actually be bufferized inplace.
static InPlaceSpec getInPlace (OpResult opResult)
Get the InPlaceSpec attribute entry kInPlaceResultsAttrName for opResult.
static InPlaceSpec getInPlace (BlockArgument bbArg)
Get inPlace information for bbArg.
static void setInPlaceFuncArgument (BlockArgument bbArg, InPlaceSpec inPlaceSpec=InPlaceSpec::True)
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void removeBufferizationFuncArguments (BlockArgument bbArg)
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static LLVM_ATTRIBUTE_UNUSED InPlaceSpec getInPlace (Value v)
static void printTensorOrBufferInfo (std::string prefix, Value value, AsmState &state, llvm::raw_ostream &os)
Helper method printing the bufferization information of a buffer / tensor.
static bool hasKnownBufferizationAliasingBehavior (Operation *op)
Return true if the op is explicitly supported by bufferization or if it has no result tensors.
static OpResult getInplaceableOpResult (TiledLoopOp op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (scf::ForOp forOp, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (LinalgOp linalgOp, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (VectorTransferOpInterface op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (InsertSliceOp op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (tensor::CastOp op, OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static OpResult getInplaceableOpResult (OpOperand &opOperand)
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
static void populateAliasingOpOperands (scf::IfOp op, OpResult result, SmallVector< OpOperand *> &operands)
Either one of the corresponding yield values from the then/else branches may alias with the result.
static SmallVector< OpOperand * > getAliasingOpOperand (OpResult result)
Determine which OpOperand* will alias with result if the op is bufferized in place.
static OpResult getAliasingOpResult (ExtractSliceOp op, OpOperand &opOperand)
If the an ExtractSliceOp is bufferized in-place, the source operand will alias with the result.
static OpResult getAliasingOpResult (OpOperand &opOperand)
Determine which OpResult will alias with opOperand if the op is bufferized in place.
static bool bufferizesToMemoryRead (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory read.
static bool isValueRead (Value value)
Return true if the given value is read by an op that bufferizes to a memory read.
static bool bufferizesToMemoryWrite (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory write.
static BufferRelation bufferRelation (OpOperand &operand)
Returns the relationship between the operand and the its corresponding OpResult that it may alias with.
static bool isInplaceMemoryWrite (OpOperand &opOperand)
Return true if opOperand has been decided to bufferize in-place.
static llvm::SetVector< Value > findValueInReverseUseDefChain (Value value, std::function< bool(Value)> condition)
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
static Value findLastPrecedingWrite (Value value)
Find the Value of the last preceding write of a given Value.
static bool happensBefore (Operation *a, Operation *b, const DominanceInfo &domInfo)
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
static Operation * getEquivalentAlloc (Value value, const BufferizationAliasInfo &aliasInfo)
Return the op with Allocate MemoryEffect if v is equivalent to an such an op.
static BlockArgument getEquivalentEnclosingFuncBBArg (Value v, const BufferizationAliasInfo &aliasInfo)
Return the first argument of the enclosing FuncOp that is equivalent to v.
static MemRefType getContiguousMemRefType (ShapedType shapedType, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
static Type getContiguousOrUnrankedMemRefType (Type type, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace=0)
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
static FunctionType getBufferizedFunctionType (MLIRContext *ctx, TypeRange argumentTypes, TypeRange resultTypes)
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
template<typename... Args>
Operation * getFirstParentOfType (Value v)
static Value createNewAllocDeallocPairForShapedValue (OpBuilder &b, Location loc, Value shapedValue, BufferizationAliasInfo &aliasInfo)
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
static Value getResultBuffer (OpBuilder &b, OpResult result, const BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, bool skipCopy=false)
Return the result buffer (memref) for a given OpResult (tensor).
static LogicalResult allocateBuffersForResults (OpBuilder &b, Location loc, LinalgOp op, SmallVectorImpl< Value > &resultBuffers, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Helper function for LinalgOp bufferization.
static LogicalResult bufferize (OpBuilder &b, LinalgOp op, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Generic conversion for any LinalgOp on tensors.
static LogicalResult bufferize (OpBuilder &b, CallOpInterface callOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
static LogicalResult bufferize (OpBuilder &b, tensor::CastOp castOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
tensor::CastOp bufferizes to memref::CastOp.
static LogicalResult bufferize (OpBuilder &b, arith::ConstantOp constantOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, GlobalCreator &globalCreator)
static LogicalResult bufferize (OpBuilder &b, tensor::DimOp dimOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
DimOp tensor operand is modified inplace.
static LogicalResult bufferize (OpBuilder &b, scf::ForOp forOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, scf::IfOp ifOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, FuncOp funcOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
FuncOp always creates TensorToMemRef ops.
static LogicalResult bufferize (OpBuilder &b, InitTensorOp initTensorOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
InitTensor always allocates (unless it was eliminated).
static LogicalResult bufferize (OpBuilder &b, ReturnOp returnOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
ReturnOp always creates memref::TensorLoadOp.
static LogicalResult bufferize (OpBuilder &b, TiledLoopOp tiledLoopOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferization for TiledLoopOp..
static LogicalResult bufferize (OpBuilder &b, ExtractSliceOp extractSliceOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferize ExtractSliceOp to subview with optional alloc + copy depending on whether or not it is marked inplaceable.
static LogicalResult bufferize (OpBuilder &b, InsertSliceOp insertSliceOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, VectorTransferOpInterface op, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, scf::YieldOp yieldOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
static LogicalResult bufferize (OpBuilder &b, linalg::YieldOp yieldOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferization for linalg::YieldOp either does not involve tensors or just results in later canonicalization.
static LogicalResult bufferize (OpBuilder &b, tensor::ExtractOp extractOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo)
Bufferization for tensor::ExtractOp just translate to memref.load, it only reads the tensor.
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand &operand, OpResult result, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place with result.
static LogicalResult bufferizableInPlaceAnalysis (ExtractSliceOp extractSliceOp, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace.
static LogicalResult bufferizableInPlaceAnalysis (OpOperand &operand, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place with one of the op's results.
static LogicalResult inPlaceAnalysisFuncOpBody (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Analyze the funcOp body to determine which OpResults are inplaceable.
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BlockAndValueMapping &bvm, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes, GlobalCreator &globalCreator)
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > &orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void applyEnablingTransformations (ModuleOp moduleOp)
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> &callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit)
static void layoutPostProcessing (ModuleOp moduleOp)
Postprocess the linalg.buffer_layout annotation across function boundaries.
static LogicalResult runInitTensorElimination (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, DominanceInfo &domInfo)
Try to eliminate InitTensorOps inside funcOp.
Variables
static constexpr int64_t kBufferAlignments = 128
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 141 of file ComprehensiveBufferize.cpp.
Referenced by bufferizeFuncOpBoundary().
DEBUG_TYPE
#define DEBUG_TYPE "comprehensive-module-bufferize"
Definition at line 133 of file ComprehensiveBufferize.cpp.
Referenced by printOperationInfo().
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X)
Definition at line 142 of file ComprehensiveBufferize.cpp.
Referenced by mlir::linalg::BufferizationAliasInfo::aliasesInPlaceWrite(), mlir::linalg::BufferizationAliasInfo::aliasesNonWritableBuffer(), bufferizableInPlaceAnalysisImpl(), bufferize(), bufferizeFuncOpInternals(), mlir::linalg::bufferizeOp(), getOrCreateBufferizedFunctionType(), happensBefore(), inPlaceAnalysisFuncOpBody(), mlir::linalg::BufferizationAliasInfo::isSourceEquivalentToAMatchingInplaceExtractSliceOp(), lookup(), map(), setInPlaceOpResult(), and mlir::linalg::BufferizationAliasInfo::wouldCreateWriteToNonWritableBuffer().
Typedef Documentation
BufferRelation
using BufferRelation = BufferizationAliasInfo::BufferRelation
Definition at line 139 of file ComprehensiveBufferize.cpp.
Enumeration Type Documentation
InPlaceSpec
enum InPlaceSpec strong
Enumerator
False
True
None
Definition at line 241 of file ComprehensiveBufferize.cpp.
Function Documentation
allocateBuffersForResults()
static LogicalResult allocateBuffersForResults (OpBuilder & b, Location loc, LinalgOp op, SmallVectorImpl< Value > & resultBuffers, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Helper function for LinalgOp bufferization.
When allocating a new buffer, analyze whether op wants to read form that buffer. Only in that case, a copy of the result buffer may be needed.
Definition at line 1542 of file ComprehensiveBufferize.cpp.
References mlir::failure(), getInplaceableOpResult(), getResultBuffer(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by bufferize().
applyEnablingTransformations()
static void applyEnablingTransformations (ModuleOp moduleOp) static
Definition at line 2793 of file ComprehensiveBufferize.cpp.
References mlir::RewritePatternSet::add(), and mlir::applyPatternsAndFoldGreedily().
Referenced by runInitTensorElimination().
bufferizableInPlaceAnalysis() [1/2]
static LogicalResult bufferizableInPlaceAnalysis (ExtractSliceOp extractSliceOp, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace.
===========================================================
When bufferized out of place, a ExtractSlice lowers to alloc + copy. This cannot change the flow of information for either the source or the result buffers.
When bufferized inplace, a ExtractSliceOp does not by itself create any read or write from memory. Instead, it has the effect of merging the alias sets of the source and the result buffers.
An analysis is required to ensure inplace bufferization would not result in RaW dependence violations.
Definition at line 2354 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysisImpl().
Referenced by mlir::linalg::inPlaceAnalysis(), and runInitTensorElimination().
bufferizableInPlaceAnalysis() [2/2]
static LogicalResult bufferizableInPlaceAnalysis (OpOperand & operand, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place with one of the op's results.
If so, set InPlaceSpec::True on the result. Otherwise, set InPlaceSpec::False on the result.
Definition at line 2366 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysisImpl(), getInplaceableOpResult(), and mlir::success().
bufferizableInPlaceAnalysisImpl()
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand & operand, OpResult result, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place with result.
If so, set InPlaceSpec::True on the result. Otherwise, set InPlaceSpec::False on the result.
Definition at line 2309 of file ComprehensiveBufferize.cpp.
References mlir::linalg::BufferizationAliasInfo::bufferizeInPlace(), mlir::linalg::BufferizationAliasInfo::bufferizeOutOfPlace(), getAliasingOpOperand(), mlir::OpOperand::getOperandNumber(), mlir::OpResult::getResultNumber(), LDBG, printValueInfo(), mlir::success(), mlir::linalg::BufferizationAliasInfo::wouldCreateReadAfterWriteInterference(), and mlir::linalg::BufferizationAliasInfo::wouldCreateWriteToNonWritableBuffer().
Referenced by bufferizableInPlaceAnalysis().
bufferize() [1/17]
static LogicalResult bufferize (OpBuilder & b, LinalgOp op, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Generic conversion for any LinalgOp on tensors.
Definition at line 1569 of file ComprehensiveBufferize.cpp.
References allocateBuffersForResults(), mlir::failed(), mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), lookup(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by bufferizeFuncOpInternals(), and mlir::linalg::bufferizeOp().
bufferize() [2/17]
static LogicalResult bufferize (OpBuilder & b, CallOpInterface callOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
For now, it is the responsibility of the callOp bufferization to allow FuncOp that are inplaceable to write inPlace.
Definition at line 1618 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::IROperand< DerivedT, IRValueT >::get(), getAssumedUniqueReturnOp(), getCalledFunction(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), mlir::OpOperand::getOperandNumber(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), mlir::Type::isa(), isaTensor(), lookup(), map(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setAttrs(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [3/17]
static LogicalResult bufferize (OpBuilder & b, tensor::CastOp castOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
tensor::CastOp bufferizes to memref::CastOp.
Definition at line 1756 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), getContiguousOrUnrankedMemRefType(), getResultBuffer(), mlir::Value::getType(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPoint().
bufferize() [4/17]
static LogicalResult bufferize (OpBuilder & b, arith::ConstantOp constantOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, GlobalCreator & globalCreator) static
Definition at line 1787 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::GlobalCreator::getGlobalFor(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [5/17]
static LogicalResult bufferize (OpBuilder & b, tensor::DimOp dimOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
DimOp tensor operand is modified inplace.
This allows leaving dead tensors behind that will get DCE'd.
Definition at line 1809 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [6/17]
static LogicalResult bufferize (OpBuilder & b, scf::ForOp forOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 1825 of file ComprehensiveBufferize.cpp.
References mlir::linalg::BufferizationAliasInfo::createAliasInfoEntry(), mlir::failure(), getResultBuffer(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), map(), and mlir::success().
bufferize() [7/17]
static LogicalResult bufferize (OpBuilder & b, scf::IfOp ifOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 1855 of file ComprehensiveBufferize.cpp.
References mlir::linalg::BufferizationAliasInfo::createAliasInfoEntry(), mlir::failure(), getResultBuffer(), map(), and mlir::success().
bufferize() [8/17]
static LogicalResult bufferize (OpBuilder & b, FuncOp funcOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
FuncOp always creates TensorToMemRef ops.
Definition at line 1881 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), map(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
bufferize() [9/17]
static LogicalResult bufferize (OpBuilder & b, InitTensorOp initTensorOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
InitTensor always allocates (unless it was eliminated).
TODO: consider hoisting across function boundaries prior to bufferization.
Definition at line 1907 of file ComprehensiveBufferize.cpp.
References createNewAllocDeallocPairForShapedValue(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [10/17]
static LogicalResult bufferize (OpBuilder & b, ReturnOp returnOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
ReturnOp always creates memref::TensorLoadOp.
Definition at line 1925 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), lookup(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [11/17]
static LogicalResult bufferize (OpBuilder & b, TiledLoopOp tiledLoopOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferization for TiledLoopOp..
Definition at line 1950 of file ComprehensiveBufferize.cpp.
References mlir::linalg::BufferizationAliasInfo::createAliasInfoEntry(), mlir::failure(), mlir::Block::getArgument(), mlir::Builder::getI32VectorAttr(), mlir::Operation::getOpOperand(), getResultBuffer(), mlir::Value::getType(), mlir::Block::insertArgument(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), lookup(), map(), resultIndex(), mlir::IROperand< DerivedT, IRValueT >::set(), and mlir::success().
bufferize() [12/17]
static LogicalResult bufferize (OpBuilder & b, ExtractSliceOp extractSliceOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferize ExtractSliceOp to subview with optional alloc + copy depending on whether or not it is marked inplaceable.
Note that getInplaceableOpResult on a ExtractSliceOp always returns null. As consequence a ExtractSliceOp always alloc + copy when taken in isolation.
If not inplaceable, copy.
Definition at line 2074 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::failure(), getInPlace(), mlir::Value::getType(), mlir::linalg::BufferizationAliasInfo::insertNewBufferAlias(), isValueRead(), LDBG, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), and True.
bufferize() [13/17]
static LogicalResult bufferize (OpBuilder & b, InsertSliceOp insertSliceOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 2126 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::failure(), getInPlace(), getResultBuffer(), mlir::Value::getType(), mlir::linalg::BufferizationAliasInfo::insertNewBufferAlias(), mlir::linalg::BufferizationAliasInfo::isSourceEquivalentToAMatchingInplaceExtractSliceOp(), LDBG, lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), and True.
bufferize() [14/17]
static LogicalResult bufferize (OpBuilder & b, VectorTransferOpInterface op, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
transfer_read from buffer always reads from the bufferized op.source().
Definition at line 2185 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::failure(), getResultBuffer(), lookup(), map(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [15/17]
static LogicalResult bufferize (OpBuilder & b, scf::YieldOp yieldOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Definition at line 2220 of file ComprehensiveBufferize.cpp.
References mlir::linalg::BufferizationAliasInfo::areEquivalentBufferizedValues(), lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [16/17]
static LogicalResult bufferize (OpBuilder & b, linalg::YieldOp yieldOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferization for linalg::YieldOp either does not involve tensors or just results in later canonicalization.
In either case it does nothing.
Definition at line 2269 of file ComprehensiveBufferize.cpp.
References isaTensor(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [17/17]
static LogicalResult bufferize (OpBuilder & b, tensor::ExtractOp extractOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo) static
Bufferization for tensor::ExtractOp just translate to memref.load, it only reads the tensor.
Definition at line 2288 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferizeFuncOpBoundary()
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
This relies on a buffer equivalence analysis of each return operand. When a result buffer is equivalent to:
a BlockArgument of funcOp, it can be dropped from the return values and becomes inplaceable at all callers. This assumes all CallOp perform the necessary work to clone operands so as to make them inplaceable. 2. an op with an Alloc effect, this currently fails bufferization but is a candidate for hoisting and creating a new inplace operand at all caller sites.
if such a hoisting for 2. is not possible (e.g. data-dependent that prevents hoisting), this is currently unsupported and will require a refcounted buffer type.
Definition at line 2591 of file ComprehensiveBufferize.cpp.
References mlir::Block::addArgument(), DBGS, mlir::Type::dyn_cast(), mlir::Block::eraseArgument(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), getAssumedUniqueReturnOp(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), mlir::Block::getNumArguments(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by runInitTensorElimination().
bufferizeFuncOpInternals()
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes, GlobalCreator & globalCreator) static
Definition at line 2486 of file ComprehensiveBufferize.cpp.
References bufferize(), mlir::linalg::bufferizeOp(), mlir::failed(), mlir::failure(), mlir::Operation::getParentOp(), LDBG, and mlir::success().
Referenced by runInitTensorElimination().
bufferizesToMemoryRead()
static bool bufferizesToMemoryRead (OpOperand & opOperand) static
Return true if opOperand bufferizes to a memory read.
Definition at line 654 of file ComprehensiveBufferize.cpp.
References mlir::detail::IROperandBase::getOwner(), hasKnownBufferizationAliasingBehavior(), and isValueRead().
Referenced by getAliasingOpResult(), and isValueRead().
bufferizesToMemoryWrite()
static bool bufferizesToMemoryWrite (OpOperand & opOperand) static
Return true if opOperand bufferizes to a memory write.
Definition at line 687 of file ComprehensiveBufferize.cpp.
References getAliasingOpResult(), mlir::detail::IROperandBase::getOwner(), and hasKnownBufferizationAliasingBehavior().
Referenced by findLastPrecedingWrite(), isInplaceMemoryWrite(), and mlir::linalg::BufferizationAliasInfo::wouldCreateWriteToNonWritableBuffer().
bufferRelation()
static BufferRelation bufferRelation (OpOperand & operand) static
Returns the relationship between the operand and the its corresponding OpResult that it may alias with.
Definition at line 713 of file ComprehensiveBufferize.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by mlir::linalg::BufferizationAliasInfo::bufferizeInPlace(), and runInitTensorElimination().
createNewAllocDeallocPairForShapedValue()
static Value createNewAllocDeallocPairForShapedValue (OpBuilder & b, Location loc, Value shapedValue, BufferizationAliasInfo & aliasInfo) static
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
Definition at line 1419 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::linalg::BufferizationAliasInfo::createAliasInfoEntry(), mlir::linalg::createOrFoldDimOp(), mlir::Type::dyn_cast(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), mlir::Region::front(), getContiguousMemRefType(), mlir::Value::getDefiningOp(), getFirstParentOfType(), mlir::Builder::getI64IntegerAttr(), mlir::Operation::getLoc(), mlir::Value::getParentBlock(), mlir::Operation::getRegion(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::linalg::BufferizationAliasInfo::insertNewBufferEquivalence(), mlir::Type::isa(), kBufferAlignments, mlir::ShapedType::kDynamicSize, mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by bufferize(), and getResultBuffer().
findLastPrecedingWrite()
static Value findLastPrecedingWrite (Value value) static
Find the Value of the last preceding write of a given Value.
Note: Unknown ops are handled conservatively and assumed to be writes. Furthermore, BlockArguments are also assumed to be writes. There is no analysis across block boundaries.
Note: To simplify the analysis, scf.if ops are considered writes. Treating a non-writing op as a writing op may introduce unnecessary out-of-place bufferizations, but is always safe from a correctness point of view.
Definition at line 920 of file ComprehensiveBufferize.cpp.
References bufferizesToMemoryWrite(), mlir::Value::cast(), findValueInReverseUseDefChain(), getAliasingOpOperand(), mlir::Value::getDefiningOp(), and hasKnownBufferizationAliasingBehavior().
Referenced by happensBefore().
findValueInReverseUseDefChain()
static llvm::SetVector<Value> findValueInReverseUseDefChain (Value value, std::function< bool(Value)> condition) static
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Find and return Values for which condition evaluates to true. OpOperands of such matching Values are not traversed any further.
When reaching the end of a chain (BlockArgument or Value without aliasing OpOperands), also return the last Value of that chain.
Example:
                          8
                          |
6* 7* +--—+-—+ | | | | 2* 3 4* 5 | | | | +-------—+-------—+-------—+ | 1
In the above example, Values with a star satisfy the condition. When starting the traversal from Value 1, the resulting SetVector is: { 2, 7, 8, 5 }
Definition at line 885 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), getAliasingOpOperand(), and mlir::Value::isa().
Referenced by findLastPrecedingWrite(), mlir::linalg::BufferizationAliasInfo::hasMatchingExtractSliceOp(), and runInitTensorElimination().
foreachCaller()
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> & callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit) static
Definition at line 2800 of file ComprehensiveBufferize.cpp.
getAliasingOpOperand()
static SmallVector<OpOperand *> getAliasingOpOperand (OpResult result) static
Determine which OpOperand* will alias with result if the op is bufferized in place.
Note that multiple OpOperands can may potentially alias with an OpResult. E.g.: std.select in the future.
Definition at line 567 of file ComprehensiveBufferize.cpp.
References mlir::Operation::dump(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), hasKnownBufferizationAliasingBehavior(), and populateAliasingOpOperands().
Referenced by bufferizableInPlaceAnalysisImpl(), findLastPrecedingWrite(), findValueInReverseUseDefChain(), getResultBuffer(), runInitTensorElimination(), mlir::linalg::BufferizationAliasInfo::wouldCreateReadAfterWriteInterference(), and mlir::linalg::BufferizationAliasInfo::wouldCreateWriteToNonWritableBuffer().
getAliasingOpResult() [1/2]
static OpResult getAliasingOpResult (ExtractSliceOp op, OpOperand & opOperand) static
If the an ExtractSliceOp is bufferized in-place, the source operand will alias with the result.
Definition at line 606 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get().
Referenced by bufferizesToMemoryWrite(), getAliasingOpResult(), happensBefore(), and isInplaceMemoryWrite().
getAliasingOpResult() [2/2]
static OpResult getAliasingOpResult (OpOperand & opOperand) static
Determine which OpResult will alias with opOperand if the op is bufferized in place.
This is a superset of getInplaceableOpResult. TODO: in the future this may need to evolve towards a list of OpResult.
Definition at line 615 of file ComprehensiveBufferize.cpp.
References bufferizesToMemoryRead(), getAliasingOpResult(), getInplaceableOpResult(), and mlir::detail::IROperandBase::getOwner().
getAssumedUniqueReturnOp()
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 168 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), and bufferizeFuncOpBoundary().
getBufferizedFunctionType()
static FunctionType getBufferizedFunctionType (MLIRContext * ctx, TypeRange argumentTypes, TypeRange resultTypes) static
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
In order for all the callers to agree, this must bufferize to the most dynamic buffer type supported. A later pass across all CallOps in the module can decide whether to simplify the types of to version according to some cost model.
Definition at line 1361 of file ComprehensiveBufferize.cpp.
References getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), and rewrite().
Referenced by getOrCreateBufferizedFunctionType().
getCalledFunction()
static FuncOp getCalledFunction (CallOpInterface callOp) static
Return the FuncOp called by callOp.
Definition at line 158 of file ComprehensiveBufferize.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by bufferize().
getContiguousMemRefType()
static MemRefType getContiguousMemRefType (ShapedType shapedType, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {}) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace.
Definition at line 1319 of file ComprehensiveBufferize.cpp.
References mlir::ShapedType::getElementType(), and mlir::ShapedType::getShape().
Referenced by createNewAllocDeallocPairForShapedValue(), and getContiguousOrUnrankedMemRefType().
getContiguousOrUnrankedMemRefType()
static Type getContiguousOrUnrankedMemRefType (Type type, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {}) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace or an UnrankedMemRefType otherwise.
Definition at line 1330 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), getContiguousMemRefType(), mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by bufferize(), and getBufferizedFunctionType().
getDynamicMemRefType()
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace = 0) static
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
The layout must be the most dynamic possible and canonicalize away once bufferization is finished.
Definition at line 1343 of file ComprehensiveBufferize.cpp.
References mlir::ShapedType::kDynamicStrideOrOffset, and mlir::makeStridedLinearLayoutMap().
Referenced by bufferize(), and getBufferizedFunctionType().
getEquivalentAlloc()
static Operation * getEquivalentAlloc (Value value, const BufferizationAliasInfo & aliasInfo) static
Return the op with Allocate MemoryEffect if v is equivalent to an such an op.
Return the op with Allocate MemoryEffect if v is equivalent to such an an op.
Return null otherwise.
Definition at line 2541 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), bufferizeFuncOpBoundary(), and mlir::linalg::BufferizationAliasInfo::dumpEquivalences().
getEquivalentEnclosingFuncBBArg()
static BlockArgument getEquivalentEnclosingFuncBBArg (Value v, const BufferizationAliasInfo & aliasInfo) static
Return the first argument of the enclosing FuncOp that is equivalent to v.
Return null if no such bbArg can be found.
Definition at line 2558 of file ComprehensiveBufferize.cpp.
References mlir::linalg::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::Value::getParentBlock(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by bufferize(), bufferizeFuncOpBoundary(), and mlir::linalg::BufferizationAliasInfo::dumpEquivalences().
getFirstParentOfType()
template<typename... Args> Operation* getFirstParentOfType (Value v)
Definition at line 1401 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), and mlir::Operation::getParentOp().
Referenced by createNewAllocDeallocPairForShapedValue().
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > & orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 2729 of file ComprehensiveBufferize.cpp.
Referenced by runInitTensorElimination().
getInPlace() [1/3]
static InPlaceSpec getInPlace (OpResult opResult) static
Get the InPlaceSpec attribute entry kInPlaceResultsAttrName for opResult.
If the result is InPlaceSpec::True, the use-def chain analysis has guaranteed that no subsequent read of the tensor value occurs and the result can be buferized inPlace. If no InPlaceSpec attribute has been set for opResult, return InPlaceSpec::None.
Definition at line 298 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, None, and symbolize().
Referenced by mlir::linalg::BufferizationAliasInfo::aliasesNonWritableBuffer(), bufferize(), getInPlace(), getResultBuffer(), isInplaceMemoryWrite(), mlir::linalg::BufferizationAliasInfo::isSourceEquivalentToAMatchingInplaceExtractSliceOp(), printTensorOrBufferInfo(), and runInitTensorElimination().
getInPlace() [2/3]
static InPlaceSpec getInPlace (BlockArgument bbArg) static
Get inPlace information for bbArg.
FuncOp allow argument attributes, we use those to encode the information. BlockArgument of other ops delegate to their owner's parent op.
Definition at line 316 of file ComprehensiveBufferize.cpp.
References False, mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::BoolAttr::getValue(), None, and True.
getInPlace() [3/3]
static LLVM_ATTRIBUTE_UNUSED InPlaceSpec getInPlace (Value v) static
Definition at line 357 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), mlir::Value::dyn_cast(), and getInPlace().
getInplaceableOpResult() [1/7]
static OpResult getInplaceableOpResult (TiledLoopOp op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 463 of file ComprehensiveBufferize.cpp.
Referenced by allocateBuffersForResults(), bufferizableInPlaceAnalysis(), getAliasingOpResult(), and getInplaceableOpResult().
getInplaceableOpResult() [2/7]
static OpResult getInplaceableOpResult (scf::ForOp forOp, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 470 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
getInplaceableOpResult() [3/7]
static OpResult getInplaceableOpResult (LinalgOp linalgOp, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 479 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::Value::getType(), and mlir::Type::isa().
getInplaceableOpResult() [4/7]
static OpResult getInplaceableOpResult (VectorTransferOpInterface op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 499 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
getInplaceableOpResult() [5/7]
static OpResult getInplaceableOpResult (InsertSliceOp op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 511 of file ComprehensiveBufferize.cpp.
getInplaceableOpResult() [6/7]
static OpResult getInplaceableOpResult (tensor::CastOp op, OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
Return null if no such result exists.
Definition at line 520 of file ComprehensiveBufferize.cpp.
getInplaceableOpResult() [7/7]
static OpResult getInplaceableOpResult (OpOperand & opOperand) static
Return the OpResult that may bufferize into the same buffer as opOperand when the op is bufferized inplace.
The inplace analysis uses this information along with interfering read analysis to determine which op results reuse the same buffer as some operand.
Definition at line 530 of file ComprehensiveBufferize.cpp.
References getInplaceableOpResult(), and mlir::detail::IROperandBase::getOwner().
getOrCreateBufferizedFunctionType()
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
Otherwise, construct a new entry based on argumentTypes and resultTypes.
Definition at line 1382 of file ComprehensiveBufferize.cpp.
References getBufferizedFunctionType(), and LDBG.
Referenced by bufferize(), and bufferizeFuncOpBoundary().
getResultBuffer()
static Value getResultBuffer (OpBuilder & b, OpResult result, const BlockAndValueMapping & bvm, BufferizationAliasInfo & aliasInfo, bool skipCopy = false) static
Return the result buffer (memref) for a given OpResult (tensor).
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization is necessary.
Definition at line 1488 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::Operation::emitError(), mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpOperand(), getInPlace(), mlir::Operation::getLoc(), mlir::OpResult::getOwner(), isInitTensorOp(), isValueRead(), lookup(), mlir::OpBuilder::setInsertionPoint(), and True.
Referenced by allocateBuffersForResults(), and bufferize().
happensBefore()
static bool happensBefore (Operation * a, Operation * b, const DominanceInfo & domInfo) static
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
Definition at line 962 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), findLastPrecedingWrite(), getAliasingOpResult(), mlir::Value::getDefiningOp(), mlir::Operation::getParentOp(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::Operation::isProperAncestor(), LDBG, printOperationInfo(), printValueInfo(), and mlir::DominanceInfo::properlyDominates().
hasKnownBufferizationAliasingBehavior()
static bool hasKnownBufferizationAliasingBehavior (Operation * op) static
Return true if the op is explicitly supported by bufferization or if it has no result tensors.
Other cases must be conservative.
Definition at line 437 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), and isaTensor().
Referenced by mlir::linalg::BufferizationAliasInfo::aliasesNonWritableBuffer(), bufferizesToMemoryRead(), bufferizesToMemoryWrite(), findLastPrecedingWrite(), and getAliasingOpOperand().
inPlaceAnalysisFuncOpBody()
static LogicalResult inPlaceAnalysisFuncOpBody (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Analyze the funcOp body to determine which OpResults are inplaceable.
Definition at line 2403 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::BoolAttr::getValue(), isaTensor(), LDBG, and mlir::linalg::BufferizationAliasInfo::setBufferizesToWritableMemory().
Referenced by runInitTensorElimination().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 155 of file ComprehensiveBufferize.cpp.
References mlir::Type::isa().
Referenced by bufferize(), bufferizeFuncOpBoundary(), mlir::linalg::bufferizeOp(), hasKnownBufferizationAliasingBehavior(), and inPlaceAnalysisFuncOpBody().
isInitTensorOp()
static bool isInitTensorOp (Value value) static
Return true if value is the result of an InitTensorOp or a cast thereof.
Definition at line 181 of file ComprehensiveBufferize.cpp.
References mlir::Value::getDefiningOp().
Referenced by getResultBuffer().
isInplaceMemoryWrite()
static bool isInplaceMemoryWrite (OpOperand & opOperand) static
Return true if opOperand has been decided to bufferize in-place.
Definition at line 726 of file ComprehensiveBufferize.cpp.
References bufferizesToMemoryWrite(), getAliasingOpResult(), getInPlace(), and True.
Referenced by mlir::linalg::BufferizationAliasInfo::aliasesInPlaceWrite().
isValueRead()
static bool isValueRead (Value value) static
Return true if the given value is read by an op that bufferizes to a memory read.
Also takes into account ops that create an alias but do not read by themselves (e.g., ExtractSliceOp).
Definition at line 633 of file ComprehensiveBufferize.cpp.
References bufferizesToMemoryRead(), mlir::detail::IROperandBase::getOwner(), and mlir::Value::getUses().
Referenced by bufferize(), bufferizesToMemoryRead(), and getResultBuffer().
layoutPostProcessing()
static void layoutPostProcessing (ModuleOp moduleOp) static
Postprocess the linalg.buffer_layout annotation across function boundaries.
This is a purely mechanical process that may later become part of a separate pass with its own layout assignment heuristic.
Definition at line 2812 of file ComprehensiveBufferize.cpp.
Referenced by runInitTensorElimination().
lookup()
static Value lookup (const BlockAndValueMapping & bvm, Value key) static
Wrapper for better debugging.
Definition at line 208 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Value::getParentBlock(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Type::isa(), LDBG, and mlir::BlockAndValueMapping::lookupOrNull().
Referenced by bufferize(), mlir::detail::InterfaceMap::contains(), getResultBuffer(), and mlir::detail::InterfaceMap::lookup().
map() [1/2]
static void map (BlockAndValueMapping & bvm, ValueRange keys, ValueRange values) static
Wrapper for better debugging.
Definition at line 193 of file ComprehensiveBufferize.cpp.
References LDBG, mlir::BlockAndValueMapping::map(), and printValueInfo().
Referenced by acceptBitWidth(), mlir::FlatAffineValueConstraints::addBound(), addNamedOpBuilders(), allocateBuffersForResults(), bufferize(), buildVectorRead(), buildVectorWrite(), calculateImplicitMap(), mlir::canonicalizeMapAndOperands(), mlir::canonicalizeSetAndOperands(), computeIterationGraph(), createFoldedComposedAffineApply(), mlir::python::PyAffineExpr::createFromCapsule(), denseUnitStrides(), mlir::vector::distributPointwiseVectorOp(), findSparseAnnotations(), foldTransferInBoundsAttribute(), mlir::linalg::fullyComposeAndAffineApply(), fuseElementwiseOpsImpl(), fuseWithReshapeByExpansion(), genBuffers(), generateCopy(), genInvariants(), genSubscript(), mlir::MemRefAccess::getAccessMap(), mlir::AffineMap::getAsOpaquePointer(), getCollapsedOutputDimFromInputShape(), mlir::getConstantTripCount(), mlir::AffineMap::getContext(), mlir::MutableAffineMap::getContext(), getDimMap(), getExpandedDimToCollapsedDimMap(), mlir::AffineMap::getFromOpaquePointer(), mlir::getLargestDivisorOfTripCount(), mlir::AffineBound::getMap(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineBound::getOperands(), mlir::gpu::getProcessor(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), getShapeDefiningLoopRange(), mlir::AffineDmaWaitOp::getTagMapAttrName(), mlir::Builder::getType(), mlir::FlatAffineConstraints::getUniverse(), hasTrivialZeroTripCount(), inlineRegionAndEmitStore(), mlir::detail::NestedAnalysisMap::invalidate(), mlir::AffineMap::isFunctionOfSymbol(), linalgOpToLoopsImpl(), logFailure(), mlir::makeComposedAffineApply(), mlir::linalg::makeTiledShapes(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), ContractExtractPattern::matchAndRewrite(), TransferReadPermutationLowering::matchAndRewrite(), TransferWritePermutationLowering::matchAndRewrite(), TransferOpReduceRank::matchAndRewrite(), mlir::MutableAffineMap::MutableAffineMap(), mlir::normalizeAffineParallel(), mlir::AffineMap::operator bool(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), mlir::AffineMap::operator==(), outlineKernelFuncImpl(), parseAffineApplyOp(), mlir::detail::Parser::parseAttribute(), parseBound(), mlir::detail::Parser::parseIntegerSetReference(), mlir::detail::Parser::parseMemRefType(), mlir::AsmParser::parseOptionalAttribute(), parseTransferReadOp(), mlir::AffineMap::print(), printBound(), mlir::AsmPrinter::Impl::printIntegerSet(), remainsLegalAfterInline(), mlir::AffineExpr::replace(), replaceUnitDims(), mlir::OpAsmParser::resolveOperands(), rewriteAffineOpAfterPeeling(), mlir::linalg::LinalgTilingOptions::scalarizeDynamicDims(), mlir::MemRefType::Builder::setMemorySpace(), mlir::sinkOperationsIntoLaunchOp(), sliceTransferIndices(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), tilePadTensorOp(), vectorizeAsLinalgGeneric(), verify(), mlir::verifyReshapeLikeShapes(), and verifyTransferOp().
map() [2/2]
static void map (BlockAndValueMapping & bvm, Value key, Value value) static
Wrapper for better debugging.
Definition at line 201 of file ComprehensiveBufferize.cpp.
References LDBG, mlir::BlockAndValueMapping::map(), and printValueInfo().
populateAliasingOpOperands()
static void populateAliasingOpOperands (scf::IfOp op, OpResult result, SmallVector< OpOperand *> & operands) static
Either one of the corresponding yield values from the then/else branches may alias with the result.
Definition at line 556 of file ComprehensiveBufferize.cpp.
Referenced by getAliasingOpOperand().
printOperationInfo()
static std::string printOperationInfo (Operation * op, bool prefix = true) static
Print the operation name and bufferization information.
Definition at line 381 of file ComprehensiveBufferize.cpp.
References DEBUG_TYPE, mlir::Operation::getName(), mlir::Operation::getOpOperands(), mlir::Operation::getOpResults(), mlir::Operation::getParentOfType(), and printTensorOrBufferInfo().
Referenced by mlir::linalg::BufferizationAliasInfo::aliasesInPlaceWrite(), happensBefore(), printValueInfo(), and setInPlaceOpResult().
printTensorOrBufferInfo()
static void printTensorOrBufferInfo (std::string prefix, Value value, AsmState & state, llvm::raw_ostream & os) static
Helper method printing the bufferization information of a buffer / tensor.
Definition at line 368 of file ComprehensiveBufferize.cpp.
References getInPlace(), mlir::Value::getType(), mlir::Type::isa(), None, mlir::Value::printAsOperand(), and stringify().
Referenced by printOperationInfo(), and printValueInfo().
printValueInfo()
static std::string printValueInfo (Value value, bool prefix = true) static
Print the bufferization information for the defining op or block argument.
Definition at line 402 of file ComprehensiveBufferize.cpp.
References mlir::Value::getDefiningOp(), mlir::Region::getParentOfType(), mlir::Value::getParentRegion(), printOperationInfo(), printTensorOrBufferInfo(), and value.
Referenced by mlir::linalg::BufferizationAliasInfo::aliasesInPlaceWrite(), mlir::linalg::BufferizationAliasInfo::aliasesNonWritableBuffer(), bufferizableInPlaceAnalysisImpl(), happensBefore(), map(), mlir::linalg::BufferizationAliasInfo::printAliases(), and mlir::linalg::BufferizationAliasInfo::printEquivalences().
removeBufferizationFuncArguments()
static void removeBufferizationFuncArguments (BlockArgument bbArg) static
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 349 of file ComprehensiveBufferize.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by runInitTensorElimination().
runInitTensorElimination()
static LogicalResult runInitTensorElimination (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, DominanceInfo & domInfo) static
Try to eliminate InitTensorOps inside funcOp.
An InitTensorOp can be eliminated if it is eventually inserted into another tensor (and some other conditions are met).
E.g.: %0 = linalg.init_tensor %1 = linalg.fill(cst, %0) {inplace = [true]} %2 = tensor.insert_slice %1 into t[10][20][1]
InitTensorOp elimination will try to fill t inplace instead of filling a new allocation %0 and inserting it into t. This is done by replacing the InitTensorOp with:
%0 = tensor.extract_slice t[10][20][1]
The analysis looks for matching ExtractSliceOp/InsertSliceOp pairs and lets those bufferize inplace in the absence of other conflicts.
Starting from an InsertSliceOp, an InitTensorOp at the end of the insert source's reverse use-def chain is eliminated if:
The InsertSliceOp was decided to bufferize inplace.
On the reverse use-def chain path from the InsertSliceOp to the InitTensorOp, all ops were decided to bufferize inplace and the buffer relation is "equivalent" (TODO: can be relaxed if needed).
The reverse use-def chain has exactly one end, which is the InitTensorOp.
Note that the newly inserted ExtractSliceOp may have to bufferize out-of-place due to RaW conflicts.
Definition at line 2918 of file ComprehensiveBufferize.cpp.
References mlir::OpPassManager::addPass(), mlir::WalkResult::advance(), applyEnablingTransformations(), bufferizableInPlaceAnalysis(), bufferizeFuncOpBoundary(), bufferizeFuncOpInternals(), bufferRelation(), mlir::linalg::BufferizationAliasInfo::createAliasInfoEntry(), mlir::createCanonicalizerPass(), mlir::createCSEPass(), mlir::createLoopInvariantCodeMotionPass(), mlir::Value::dyn_cast(), mlir::failed(), mlir::failure(), findValueInReverseUseDefChain(), getAliasingOpOperand(), mlir::Value::getDefiningOp(), getFuncOpsOrderedByCalls(), getInPlace(), mlir::Value::getLoc(), inPlaceAnalysisFuncOpBody(), mlir::WalkResult::interrupt(), kInPlaceResultsAttrName, layoutPostProcessing(), mlir::Operation::removeAttr(), removeBufferizationFuncArguments(), mlir::Value::replaceAllUsesWith(), setInPlaceFuncArgument(), mlir::WalkResult::skip(), and True.
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, InPlaceSpec inPlaceSpec = InPlaceSpec::True) static
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 339 of file ComprehensiveBufferize.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), and True.
Referenced by runInitTensorElimination().
setInPlaceOpResult()
static void setInPlaceOpResult (OpResult opResult, InPlaceSpec inPlace = InPlaceSpec::True) static
Mark whether OpResult can actually be bufferized inplace.
If inPlace is InPlaceSpec::True, the use-def chain analysis has guaranteed that no subsequent write would occur to the bufferized tensor value (i.e. the result can be bufferized inPlace).
Definition at line 271 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::Operation::getNumResults(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, LDBG, None, printOperationInfo(), mlir::Operation::setAttr(), and stringify().
Referenced by mlir::linalg::BufferizationAliasInfo::bufferizeInPlace(), and mlir::linalg::BufferizationAliasInfo::bufferizeOutOfPlace().
stringify()
static StringRef stringify (InPlaceSpec val) static
Definition at line 247 of file ComprehensiveBufferize.cpp.
References False, None, and True.
Referenced by parseOptionalLLVMKeyword(), printTensorOrBufferInfo(), and setInPlaceOpResult().
symbolize()
static Optional<InPlaceSpec> symbolize (StringRef str) static
Definition at line 259 of file ComprehensiveBufferize.cpp.
References False, None, and True.
Referenced by getInPlace().
Variable Documentation
kBufferAlignments
constexpr int64_t kBufferAlignments = 128 static
Definition at line 145 of file ComprehensiveBufferize.cpp.
Referenced by createNewAllocDeallocPairForShapedValue().
kInPlaceResultsAttrName
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Definition at line 238 of file ComprehensiveBufferize.cpp.
Referenced by getInPlace(), runInitTensorElimination(), and setInPlaceOpResult().