MLIR: lib/Conversion/VectorToLLVM/ConvertVectorToLLVM.cpp File Reference
ConvertVectorToLLVM.cpp File Reference
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Conversion/LLVMCommon/VectorPattern.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/LLVMIR/FunctionCallUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorRewritePatterns.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Target/LLVMIR/TypeToLLVM.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static VectorType reducedVectorTypeFront (VectorType tp)
static VectorType reducedVectorTypeBack (VectorType tp)
static Value insertOne (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, Value val1, Value val2, Type llvmType, int64_t rank, int64_t pos)
static Value extractOne (ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, Location loc, Value val, Type llvmType, int64_t rank, int64_t pos)
LogicalResult getMemRefAlignment (LLVMTypeConverter &typeConverter, MemRefType memrefType, unsigned &align)
static unsigned getAssumedAlignment (Value value)
template<class OpAdaptor >
LogicalResult getMemRefOpAlignment (LLVMTypeConverter &typeConverter, OpAdaptor op, unsigned &align)
static LogicalResult getIndexedPtrs (ConversionPatternRewriter &rewriter, Location loc, Value memref, Value base, Value index, MemRefType memRefType, VectorType vType, Value &ptrs)
static Value castDataPtr (ConversionPatternRewriter &rewriter, Location loc, Value ptr, MemRefType memRefType, Type vt)
Function Documentation
castDataPtr()
static Value castDataPtr (ConversionPatternRewriter & rewriter, Location loc, Value ptr, MemRefType memRefType, Type vt) static
Definition at line 131 of file ConvertVectorToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::LLVM::LLVMPointerType::get(), mlir::Builder::getI32IntegerAttr(), getIndexedPtrs(), getMemRefOpAlignment(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
extractOne()
static Value extractOne (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, Value val, Type llvmType, int64_t rank, int64_t pos) static
Definition at line 57 of file ConvertVectorToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), and mlir::Builder::getIntegerAttr().
getAssumedAlignment()
static unsigned getAssumedAlignment (Value value) static
Definition at line 89 of file ConvertVectorToLLVM.cpp.
References mlir::Value::getUses(), and mlir::lcm().
Referenced by getMemRefOpAlignment().
getIndexedPtrs()
static LogicalResult getIndexedPtrs (ConversionPatternRewriter & rewriter, Location loc, Value memref, Value base, Value index, MemRefType memRefType, VectorType vType, Value & ptrs) static
Definition at line 113 of file ConvertVectorToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::MemRefDescriptor::getElementPtrType(), mlir::LLVM::getFixedVectorType(), mlir::getStridesAndOffset(), and mlir::success().
Referenced by castDataPtr().
getMemRefAlignment()
LogicalResult getMemRefAlignment (LLVMTypeConverter & typeConverter, MemRefType memrefType, unsigned & align)
Definition at line 73 of file ConvertVectorToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::failure(), mlir::LLVMTypeConverter::getDataLayout(), mlir::LLVM::TypeToLLVMIRTranslator::getPreferredAlignment(), and mlir::success().
Referenced by getMemRefOpAlignment().
getMemRefOpAlignment()
template<class OpAdaptor > LogicalResult getMemRefOpAlignment (LLVMTypeConverter & typeConverter, OpAdaptor op, unsigned & align)
Definition at line 103 of file ConvertVectorToLLVM.cpp.
References mlir::failed(), mlir::failure(), getAssumedAlignment(), getMemRefAlignment(), max(), and mlir::success().
Referenced by castDataPtr().
insertOne()
static Value insertOne (ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, Location loc, Value val1, Value val2, Type llvmType, int64_t rank, int64_t pos) static
Definition at line 40 of file ConvertVectorToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), and mlir::Builder::getIntegerAttr().
reducedVectorTypeBack()
static VectorType reducedVectorTypeBack (VectorType tp) static
Definition at line 34 of file ConvertVectorToLLVM.cpp.
reducedVectorTypeFront()
static VectorType reducedVectorTypeFront (VectorType tp) static
Definition at line 28 of file ConvertVectorToLLVM.cpp.