MLIR: lib/Dialect/Linalg/Transforms/HoistPadding.cpp File Reference
HoistPadding.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/HoistPadding.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SCF/Utils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/LoopUtils.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
Classes
struct HoistingAnalysis
Analysis class to support PadTensorOp hoisting across multiple enclosing loops.
Macros
#define DEBUG_TYPE "hoist-padding"
#define DBGS() (dbgs() << '[' << DEBUG_TYPE << "] ")
Functions
static bool isOnlyUsedAsInputOfLinalgOp (PadTensorOp padTensorOp)
Return true if all uses of padTensorOp are an input tensor of some LinalgOp.
static void getAtMostNEnclosingLoops (PadTensorOp padTensorOp, int nLevels, SmallVector< scf::ForOp > &reverseEnclosingLoops)
Return at most nLevels of immediately enclosing scf::ForOp loops.
static bool isDefinedOutsideOrConstant (scf::ForOp outer, Value v)
static LogicalResult foldUpperBoundsIntoConstraintsSet (FlatAffineValueConstraints &constraints, scf::ForOp outerLimit, ArrayRef< scf::ForOp > loops)
For each loop in loops, determine the ops involved in the construction of its upper bound—up to the outerLimit loop— and fold them as new inequalities in the constraint set.
template<typename... OpTypeList>
static bool backwardsSliceOnlyHasOpsOfType (scf::ForOp outerLimit, Value v)
Return success if v is a value that is only transitively defined by ops of type in OpTypeList.
static Value buildLoopIterationCount (OpBuilder &b, scf::ForOp outer, scf::ForOp forOp)
Return the current iteration number in the loop (iv - lb).ceilDiv(step).
Macro Definition Documentation
DBGS
#define DBGS () (dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 38 of file HoistPadding.cpp.
Referenced by backwardsSliceOnlyHasOpsOfType(), getAtMostNEnclosingLoops(), HoistingAnalysis::HoistingAnalysis(), mlir::linalg::hoistPaddingOnTensors(), and isOnlyUsedAsInputOfLinalgOp().
DEBUG_TYPE
#define DEBUG_TYPE "hoist-padding"
Definition at line 36 of file HoistPadding.cpp.
Function Documentation
backwardsSliceOnlyHasOpsOfType()
template<typename... OpTypeList> static bool backwardsSliceOnlyHasOpsOfType (scf::ForOp outerLimit, Value v) static
Return success if v is a value that is only transitively defined by ops of type in OpTypeList.
Definition at line 342 of file HoistPadding.cpp.
References HoistingAnalysis::backwardSlice, DBGS, and mlir::getBackwardSlice().
buildLoopIterationCount()
static Value buildLoopIterationCount (OpBuilder & b, scf::ForOp outer, scf::ForOp forOp) static
Return the current iteration number in the loop (iv - lb).ceilDiv(step).
The returned Value is guaranteed not to depend on any loop comprised in [outer, forOp]. Return null if such a loop-independent quantity cannot be computed.
Definition at line 363 of file HoistPadding.cpp.
References mlir::detail::bindDims(), mlir::detail::bindSymbols(), mlir::ceilDiv(), mlir::OpBuilder::createOrFold(), mlir::Value::getLoc(), and isDefinedOutsideOrConstant().
Referenced by mlir::linalg::hoistPaddingOnTensors().
foldUpperBoundsIntoConstraintsSet()
static LogicalResult foldUpperBoundsIntoConstraintsSet (FlatAffineValueConstraints & constraints, scf::ForOp outerLimit, ArrayRef< scf::ForOp > loops) static
For each loop in loops, determine the ops involved in the construction of its upper bound—up to the outerLimit loop— and fold them as new inequalities in the constraint set.
This is achieved by computing the backwardSlice of the loop's upper bound and iteratively folding each op in reverse topological order to guarantee use-def ordering. As operations are folded in, their result is projected out of the constraints set. The following operations are supported:
scf::ForOp are simply skipped.
AffineApplyOp are composed to replace the result by an equality.
AffineMinOp are composed by adding each entry as an upper bound. If any other operation is met, return failure.
Definition at line 211 of file HoistPadding.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::FlatAffineValueConstraints::appendDimId(), HoistingAnalysis::backwardSlice, mlir::FlatAffineValueConstraints::composeMap(), mlir::FlatAffineValueConstraints::computeAlignedMap(), mlir::FlatAffineValueConstraints::containsId(), mlir::failed(), mlir::failure(), mlir::FlatAffineValueConstraints::findId(), mlir::getBackwardSlice(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::Operation::getOperands(), mlir::Operation::getResult(), mlir::Operation::getResults(), isDefinedOutsideOrConstant(), mlir::FlatAffineValueConstraints::projectOut(), and mlir::success().
Referenced by HoistingAnalysis::getPackedTensorSizes().
getAtMostNEnclosingLoops()
static void getAtMostNEnclosingLoops (PadTensorOp padTensorOp, int nLevels, SmallVector< scf::ForOp > & reverseEnclosingLoops) static
Return at most nLevels of immediately enclosing scf::ForOp loops.
Stops at the first parent that is not an scf::ForOp. Multi-loops such as scf.parallel or linalg.tiled_loop are not modeled atm. Control-flow and other containing ops with regions are not modeled atm.
Definition at line 111 of file HoistPadding.cpp.
References DBGS, and mlir::Operation::getParentOp().
Referenced by HoistingAnalysis::HoistingAnalysis().
isDefinedOutsideOrConstant()
static bool isDefinedOutsideOrConstant (scf::ForOp outer, Value v) static
Definition at line 192 of file HoistPadding.cpp.
References mlir::Value::getDefiningOp().
Referenced by buildLoopIterationCount(), and foldUpperBoundsIntoConstraintsSet().
isOnlyUsedAsInputOfLinalgOp()
static bool isOnlyUsedAsInputOfLinalgOp (PadTensorOp padTensorOp) static
Return true if all uses of padTensorOp are an input tensor of some LinalgOp.
Definition at line 92 of file HoistPadding.cpp.
References DBGS.
Referenced by HoistingAnalysis::HoistingAnalysis().