MLIR: lib/Pass/IRPrinting.cpp File Reference
IRPrinting.cpp File Reference
#include "PassDetail.h"
#include "mlir/Pass/PassManager.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/SHA1.h"
Functions
static void printIR (Operation *op, bool printModuleScope, raw_ostream &out, OpPrintingFlags flags)
Function Documentation
printIR()
static void printIR (Operation * op, bool printModuleScope, raw_ostream & out, OpPrintingFlags flags) static
Definition at line 97 of file IRPrinting.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getBlock(), mlir::Operation::getName(), mlir::Pass::getName(), mlir::SymbolTable::getSymbolAttrName(), mlir::Operation::print(), mlir::OpPrintingFlags::printGenericOpForm(), and mlir::OpPrintingFlags::useLocalScope().