MLIR: lib/Conversion/LLVMCommon/MemRefBuilder.cpp File Reference
MemRefBuilder.cpp File Reference
#include "mlir/Conversion/LLVMCommon/MemRefBuilder.h"
#include "MemRefDescriptor.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/Support/MathExtras.h"
Functions
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
Function Documentation
createIndexAttrConstant()
static Value createIndexAttrConstant (OpBuilder & builder, Location loc, Type resultType, int64_t value) static
Definition at line 100 of file MemRefBuilder.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), and mlir::StructBuilder::value.
Referenced by mlir::UnrankedMemRefDescriptor::alignedPtr(), mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::UnrankedMemRefDescriptor::offset(), mlir::UnrankedMemRefDescriptor::setAlignedPtr(), mlir::MemRefDescriptor::setConstantOffset(), mlir::MemRefDescriptor::setConstantSize(), mlir::MemRefDescriptor::setConstantStride(), mlir::UnrankedMemRefDescriptor::setOffset(), mlir::MemRefDescriptor::size(), and mlir::UnrankedMemRefDescriptor::sizeBasePtr().