MLIR: lib/Dialect/LLVMIR/IR/NVVMDialect.cpp File Reference
NVVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/NVVMOpsDialect.cpp.inc"
#include "mlir/Dialect/LLVMIR/NVVMOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printNVVMIntrinsicOp (OpAsmPrinter &p, Operation *op)
static ParseResult parseNVVMShflSyncBflyOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseNVVMVoteBallotOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (MmaOp op)
template<typename T >
static LogicalResult verifyWMMALoadOp (T op, StringRef operand)
static LogicalResult verify (WMMALoadAM16N16K16Op op)
static LogicalResult verify (WMMALoadBM16N16K16Op op)
static LogicalResult verify (WMMALoadCF16M16N16K16Op op)
static LogicalResult verify (WMMALoadCF32M16N16K16Op op)
template<typename T >
static bool verifyWMMAStoreOp (T op, SmallVector< Type > &containedElems)
static LogicalResult verify (WMMAStoreF16M16N16K16Op op)
static LogicalResult verify (WMMAStoreF32M16N16K16Op op)
static LogicalResult verify (WMMAMmaF16F16M16N16K16Op op)
static LogicalResult parseWMMAMmaF16F16M16N16K16Op (OpAsmParser &parser, OperationState &result)
static void printWMMAMmaF16F16M16N16K16Op (OpAsmPrinter &p, WMMAMmaF16F16M16N16K16Op &op)
static LogicalResult verify (WMMAMmaF32F32M16N16K16Op op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 361 of file NVVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseNVVMShflSyncBflyOp()
static ParseResult parseNVVMShflSyncBflyOp (OpAsmParser & parser, OperationState & result) static
Definition at line 48 of file NVVMDialect.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::failure(), mlir::AsmParser::getContext(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseNVVMVoteBallotOp()
static ParseResult parseNVVMVoteBallotOp (OpAsmParser & parser, OperationState & result) static
Definition at line 73 of file NVVMDialect.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getContext(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseWMMAMmaF16F16M16N16K16Op()
static LogicalResult parseWMMAMmaF16F16M16N16K16Op (OpAsmParser & parser, OperationState & result) static
Definition at line 262 of file NVVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseArrow(), mlir::AsmParser::parseColon(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
printNVVMIntrinsicOp()
static void printNVVMIntrinsicOp (OpAsmPrinter & p, Operation * op) static
Definition at line 39 of file NVVMDialect.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getOperands(), and mlir::Operation::getResultTypes().
printWMMAMmaF16F16M16N16K16Op()
static void printWMMAMmaF16F16M16N16K16Op (OpAsmPrinter & p, WMMAMmaF16F16M16N16K16Op & op) static
Definition at line 286 of file NVVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
verify() [1/9]
static LogicalResult verify (MmaOp op) static
Definition at line 89 of file NVVMDialect.cpp.
References mlir::LLVM::getFixedVectorType(), mlir::LLVM::LLVMStructType::getLiteral(), and mlir::success().
verify() [2/9]
static LogicalResult verify (WMMALoadAM16N16K16Op op) static
Definition at line 177 of file NVVMDialect.cpp.
References verifyWMMALoadOp().
verify() [3/9]
static LogicalResult verify (WMMALoadBM16N16K16Op op) static
Definition at line 181 of file NVVMDialect.cpp.
References verifyWMMALoadOp().
verify() [4/9]
static LogicalResult verify (WMMALoadCF16M16N16K16Op op) static
Definition at line 185 of file NVVMDialect.cpp.
References verifyWMMALoadOp().
verify() [5/9]
static LogicalResult verify (WMMALoadCF32M16N16K16Op op) static
Definition at line 189 of file NVVMDialect.cpp.
References verifyWMMALoadOp().
verify() [6/9]
static LogicalResult verify (WMMAStoreF16M16N16K16Op op) static
Definition at line 203 of file NVVMDialect.cpp.
References mlir::LLVM::LLVMPointerType::get(), mlir::FloatType::getF16(), mlir::success(), and verifyWMMAStoreOp().
verify() [7/9]
static LogicalResult verify (WMMAStoreF32M16N16K16Op op) static
Definition at line 222 of file NVVMDialect.cpp.
References mlir::LLVM::LLVMPointerType::get(), mlir::FloatType::getF32(), mlir::success(), and verifyWMMAStoreOp().
verify() [8/9]
static LogicalResult verify (WMMAMmaF16F16M16N16K16Op op) static
Definition at line 244 of file NVVMDialect.cpp.
References mlir::FloatType::getF16(), mlir::LLVM::LLVMStructType::getLiteral(), and mlir::success().
verify() [9/9]
static LogicalResult verify (WMMAMmaF32F32M16N16K16Op op) static
Definition at line 298 of file NVVMDialect.cpp.
References mlir::Operation::emitError(), mlir::FloatType::getF16(), mlir::FloatType::getF32(), mlir::LLVM::LLVMStructType::getLiteral(), and mlir::success().
verifyWMMALoadOp()
template<typename T > static LogicalResult verifyWMMALoadOp (T op, StringRef operand) static
Definition at line 136 of file NVVMDialect.cpp.
References mlir::LLVM::LLVMPointerType::get(), mlir::FloatType::getF16(), mlir::FloatType::getF32(), mlir::LLVM::LLVMStructType::getLiteral(), and mlir::success().
Referenced by verify().
verifyWMMAStoreOp()
template<typename T > static bool verifyWMMAStoreOp (T op, SmallVector< Type > & containedElems) static
Definition at line 194 of file NVVMDialect.cpp.
Referenced by verify().