MLIR: lib/Rewrite/PatternApplicator.cpp File Reference
PatternApplicator.cpp File Reference
#include "mlir/Rewrite/PatternApplicator.h"
#include "ByteCode.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "pattern-application"
Functions
static void logImpossibleToMatch (const Pattern &pattern)
Log a message for a pattern that is impossible to match.
static Operation * getDumpRootOp (Operation *op)
Log IR after pattern application.
static void logSucessfulPatternApplication (Operation *op)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pattern-application"
Definition at line 18 of file PatternApplicator.cpp.
Function Documentation
getDumpRootOp()
static Operation* getDumpRootOp (Operation * op) static
Log IR after pattern application.
Definition at line 42 of file PatternApplicator.cpp.
References mlir::Operation::getParentWithTrait().
Referenced by mlir::PatternApplicator::matchAndRewrite().
logImpossibleToMatch()
static void logImpossibleToMatch (const Pattern & pattern) static
Log a message for a pattern that is impossible to match.
Definition at line 35 of file PatternApplicator.cpp.
References mlir::Pattern::getRootKind().
Referenced by mlir::PatternApplicator::applyCostModel().
logSucessfulPatternApplication()
static void logSucessfulPatternApplication (Operation * op) static
Definition at line 45 of file PatternApplicator.cpp.
References mlir::Operation::dump().
Referenced by mlir::PatternApplicator::matchAndRewrite().