MLIR: lib/CAPI/Registration/Registration.cpp File Reference
Registration.cpp File Reference
#include "mlir-c/Registration.h"
#include "mlir/CAPI/IR.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllPasses.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
Functions
void mlirRegisterAllDialects (MlirContext context)
Registers all dialects known to core MLIR with the provided Context.
void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
void mlirRegisterAllPasses ()
Register all compiler passes of MLIR.
Function Documentation
mlirRegisterAllDialects()
void mlirRegisterAllDialects (MlirContext context)
Registers all dialects known to core MLIR with the provided Context.
This is needed before creating IR for these Dialects. TODO: Remove this function once the real registration API is finished.
Definition at line 16 of file Registration.cpp.
References mlir::registerAllDialects(), and unwrap().
Referenced by mlir::python::PyMlirContext::createNewContextForInit().
mlirRegisterAllLLVMTranslations()
void mlirRegisterAllLLVMTranslations (MlirContext context)
Register all translations to LLVM IR for dialects that can support it.
Definition at line 22 of file Registration.cpp.
References mlir::registerLLVMDialectTranslation(), and unwrap().
mlirRegisterAllPasses()
void mlirRegisterAllPasses ()
Register all compiler passes of MLIR.
Definition at line 26 of file Registration.cpp.
References mlir::registerAllPasses().
Referenced by PYBIND11_MODULE().