MLIR: mlir::linalg::CodegenStrategy Struct Reference
mlir::linalg::CodegenStrategy Struct Reference
Codegen strategy controls how a Linalg op is progressively lowered.
#include "mlir/Dialect/Linalg/Transforms/CodegenStrategy.h"
Public Member Functions
CodegenStrategy & tile (StringRef opName, linalg::LinalgTilingOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to add a level of tiling for Op opName with tiling options.
CodegenStrategy & tileIf (bool b, StringRef opName, linalg::LinalgTilingOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
CodegenStrategy & promote (StringRef opName, linalg::LinalgPromotionOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
CodegenStrategy & promoteIf (bool b, StringRef opName, linalg::LinalgPromotionOptions options, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
CodegenStrategy & generalize (StringRef opName, LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to generalize named operations.
CodegenStrategy & generalizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to generalize named operations.
CodegenStrategy & interchange (ArrayRef< int64_t > iteratorInterchange, LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to interchange iterators.
CodegenStrategy & interchangeIf (bool b, ArrayRef< int64_t > iteratorInterchange, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to interchange iterators.
CodegenStrategy & vectorize (StringRef opName, LinalgTransformationFilter::FilterFunction f=nullptr)
Append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & vectorizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f=nullptr)
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & setVectorTransformsOptions (vector::VectorTransformsOptions options)
Configure the post staged-patterns late vector transformations.
CodegenStrategy & setVectorTransferToSCFOptions (VectorTransferToSCFOptions options)
Configure the post staged-patterns late vector.transfer to scf conversion.
CodegenStrategy & setEnableLICM (bool val)
Configure the application of late transformations.
CodegenStrategy & setEnableHoistRedundantVectorTransfers (bool val)
CodegenStrategy & setEnableHoistRedundantVectorTransfersOnTensor (bool val)
CodegenStrategy & setMaxTransferRank (int64_t val)
CodegenStrategy & setEnableVectorTransferLowering (bool val)
CodegenStrategy & setEnableVectorTransferPartialRewrite (bool val)
CodegenStrategy & setEnableVectorContractLowering (bool val)
CodegenStrategy & setEnableVectorToSCFConversion (bool val)
void configurePassPipeline (OpPassManager &pm, MLIRContext *context) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Detailed Description
Codegen strategy controls how a Linalg op is progressively lowered.
Definition at line 117 of file CodegenStrategy.h.
Member Function Documentation
configurePassPipeline()
void mlir::linalg::CodegenStrategy::configurePassPipeline (OpPassManager & pm, MLIRContext * context) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Definition at line 31 of file CodegenStrategy.cpp.
References mlir::OpPassManager::addPass(), mlir::createLinalgStrategyEnablePass(), mlir::createLinalgStrategyLowerVectorsPass(), mlir::createLinalgStrategyRemoveMarkersPass(), mlir::linalg::LinalgVectorLoweringOptions::enableVectorContractLowering, mlir::linalg::LinalgVectorLoweringOptions::enableVectorToSCFConversion, mlir::linalg::LinalgVectorLoweringOptions::enableVectorTransferLowering, mlir::linalg::LinalgVectorLoweringOptions::enableVectorTransferPartialRewrite, mlir::Identifier::get(), mlir::linalg::LinalgVectorLoweringOptions::maxTransferRank, mlir::linalg::LinalgVectorLoweringOptions::vectorTransferToSCFOptions, and mlir::linalg::LinalgVectorLoweringOptions::vectorTransformOptions.
generalize()
CodegenStrategy& mlir::linalg::CodegenStrategy::generalize (StringRef opName, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to generalize named operations.
Definition at line 153 of file CodegenStrategy.h.
generalizeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::generalizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to generalize named operations.
Definition at line 161 of file CodegenStrategy.h.
interchange()
CodegenStrategy& mlir::linalg::CodegenStrategy::interchange (ArrayRef< int64_t > iteratorInterchange, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to interchange iterators.
Definition at line 168 of file CodegenStrategy.h.
interchangeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::interchangeIf (bool b, ArrayRef< int64_t > iteratorInterchange, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to interchange iterators.
Definition at line 176 of file CodegenStrategy.h.
promote()
CodegenStrategy& mlir::linalg::CodegenStrategy::promote (StringRef opName, linalg::LinalgPromotionOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 137 of file CodegenStrategy.h.
promoteIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::promoteIf (bool b, StringRef opName, linalg::LinalgPromotionOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 146 of file CodegenStrategy.h.
setEnableHoistRedundantVectorTransfers()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableHoistRedundantVectorTransfers (bool val) inline
Definition at line 218 of file CodegenStrategy.h.
setEnableHoistRedundantVectorTransfersOnTensor()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableHoistRedundantVectorTransfersOnTensor (bool val) inline
Definition at line 222 of file CodegenStrategy.h.
setEnableLICM()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableLICM (bool val) inline
Configure the application of late transformations.
Definition at line 214 of file CodegenStrategy.h.
setEnableVectorContractLowering()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorContractLowering (bool val) inline
Definition at line 239 of file CodegenStrategy.h.
setEnableVectorToSCFConversion()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorToSCFConversion (bool val) inline
Definition at line 243 of file CodegenStrategy.h.
setEnableVectorTransferLowering()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorTransferLowering (bool val) inline
Definition at line 231 of file CodegenStrategy.h.
setEnableVectorTransferPartialRewrite()
CodegenStrategy& mlir::linalg::CodegenStrategy::setEnableVectorTransferPartialRewrite (bool val) inline
Definition at line 235 of file CodegenStrategy.h.
setMaxTransferRank()
CodegenStrategy& mlir::linalg::CodegenStrategy::setMaxTransferRank (int64_t val) inline
Definition at line 227 of file CodegenStrategy.h.
setVectorTransferToSCFOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransferToSCFOptions (VectorTransferToSCFOptions options) inline
Configure the post staged-patterns late vector.transfer to scf conversion.
Definition at line 207 of file CodegenStrategy.h.
References options.
setVectorTransformsOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransformsOptions (vector::VectorTransformsOptions options) inline
Configure the post staged-patterns late vector transformations.
Definition at line 200 of file CodegenStrategy.h.
References options.
tile()
CodegenStrategy& mlir::linalg::CodegenStrategy::tile (StringRef opName, linalg::LinalgTilingOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to add a level of tiling for Op opName with tiling options.
Definition at line 121 of file CodegenStrategy.h.
tileIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::tileIf (bool b, StringRef opName, linalg::LinalgTilingOptions options, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 130 of file CodegenStrategy.h.
References mlir::tile().
vectorize()
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorize (StringRef opName, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 183 of file CodegenStrategy.h.
vectorizeIf()
CodegenStrategy& mlir::linalg::CodegenStrategy::vectorizeIf (bool b, StringRef opName, LinalgTransformationFilter::FilterFunction f = nullptr) inline
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 193 of file CodegenStrategy.h.
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/CodegenStrategy.h
lib/Dialect/Linalg/Transforms/CodegenStrategy.cpp