MLIR: lib/IR/SymbolTable.cpp File Reference
SymbolTable.cpp File Reference
#include "mlir/IR/SymbolTable.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "mlir/IR/SymbolInterfaces.cpp.inc"
Functions
static bool isPotentiallyUnknownSymbolTable (Operation *op)
Return true if the given operation is unknown and may potentially define a symbol table.
static StringAttr getNameIfSymbol (Operation *op)
Returns the string name of the given symbol, or null if this is not a symbol.
static StringAttr getNameIfSymbol (Operation *op, Identifier symbolAttrNameId)
static LogicalResult collectValidReferencesFor (Operation *symbol, StringAttr symbolName, Operation *within, SmallVectorImpl< SymbolRefAttr > &results)
Computes the nested symbol reference attribute for the symbol 'symbolName' that are usable within the symbol table operations from 'symbol' as far up to the given operation 'within', where 'within' is an ancestor of 'symbol'.
static Optional< WalkResult > walkSymbolTable (MutableArrayRef< Region > regions, function_ref< Optional< WalkResult >(Operation *)> callback)
Walk all of the operations within the given set of regions, without traversing into any nested symbol tables.
static LogicalResult lookupSymbolInImpl (Operation *symbolTableOp, SymbolRefAttr symbol, SmallVectorImpl< Operation *> &symbols, function_ref< Operation *(Operation *, StringAttr)> lookupSymbolFn)
Internal implementation of lookupSymbolIn that allows for specialized implementations of the lookup function.
static WalkResult walkSymbolRefs (Operation *op, function_ref< WalkResult(SymbolTable::SymbolUse, ArrayRef< int >)> callback)
Walk all of the symbol references within the given operation, invoking the provided callback for each found use.
static Optional< WalkResult > walkSymbolUses (MutableArrayRef< Region > regions, function_ref< WalkResult(SymbolTable::SymbolUse, ArrayRef< int >)> callback)
Walk all of the uses, for any symbol, that are nested within the given regions, invoking the provided callback for each.
static Optional< WalkResult > walkSymbolUses (Operation *from, function_ref< WalkResult(SymbolTable::SymbolUse, ArrayRef< int >)> callback)
Walk all of the uses, for any symbol, that are nested within the given operation 'from', invoking the provided callback for each.
static SmallVector< SymbolScope, 2 > collectSymbolScopes (Operation *symbol, Operation *limit)
Collect all of the symbol scopes from 'symbol' to (inclusive) 'limit'.
static SmallVector< SymbolScope, 2 > collectSymbolScopes (Operation *symbol, Region *limit)
template<typename IRUnit >
static SmallVector< SymbolScope, 1 > collectSymbolScopes (StringAttr symbol, IRUnit *limit)
static bool isReferencePrefixOf (SymbolRefAttr subRef, SymbolRefAttr ref)
Returns true if the given reference 'SubRef' is a sub reference of the reference 'ref', i.e.
template<typename FromT >
static Optional< SymbolTable::UseRange > getSymbolUsesImpl (FromT from)
The implementation of SymbolTable::getSymbolUses below.
template<typename SymbolT , typename IRUnitT >
static Optional< SymbolTable::UseRange > getSymbolUsesImpl (SymbolT symbol, IRUnitT *limit)
The implementation of SymbolTable::getSymbolUses below.
template<typename SymbolT , typename IRUnitT >
static bool symbolKnownUseEmptyImpl (SymbolT symbol, IRUnitT *limit)
The implementation of SymbolTable::symbolKnownUseEmpty below.
static Attribute rebuildAttrAfterRAUW (Attribute container, ArrayRef< std::pair< SmallVector< int, 1 >, SymbolRefAttr >> accesses, unsigned depth)
Rebuild the given attribute container after replacing all references to a symbol with the updated attribute in 'accesses'.
static SymbolRefAttr generateNewRefAttr (SymbolRefAttr oldAttr, FlatSymbolRefAttr newLeafAttr)
Generates a new symbol reference attribute with a new leaf reference.
template<typename SymbolT , typename IRUnitT >
static LogicalResult replaceAllSymbolUsesImpl (SymbolT symbol, StringAttr newSymbol, IRUnitT *limit)
The implementation of SymbolTable::replaceAllSymbolUses below.
Function Documentation
collectSymbolScopes() [1/3]
static SmallVector<SymbolScope, 2> collectSymbolScopes (Operation * symbol, Operation * limit) static
Collect all of the symbol scopes from 'symbol' to (inclusive) 'limit'.
Definition at line 612 of file SymbolTable.cpp.
References collectValidReferencesFor(), mlir::SymbolTable::getNearestSymbolTable(), mlir::Operation::getParentOp(), mlir::SymbolTable::getSymbolName(), mlir::Operation::hasTrait(), and mlir::succeeded().
Referenced by collectSymbolScopes(), getSymbolUsesImpl(), replaceAllSymbolUsesImpl(), and symbolKnownUseEmptyImpl().
collectSymbolScopes() [2/3]
static SmallVector<SymbolScope, 2> collectSymbolScopes (Operation * symbol, Region * limit) static
Definition at line 672 of file SymbolTable.cpp.
References collectSymbolScopes(), and mlir::Region::getParentOp().
collectSymbolScopes() [3/3]
template<typename IRUnit > static SmallVector<SymbolScope, 1> collectSymbolScopes (StringAttr symbol, IRUnit * limit) static
Definition at line 683 of file SymbolTable.cpp.
collectValidReferencesFor()
static LogicalResult collectValidReferencesFor (Operation * symbol, StringAttr symbolName, Operation * within, SmallVectorImpl< SymbolRefAttr > & results) static
Computes the nested symbol reference attribute for the symbol 'symbolName' that are usable within the symbol table operations from 'symbol' as far up to the given operation 'within', where 'within' is an ancestor of 'symbol'.
Returns success if all references up to 'within' could be computed.
Definition at line 39 of file SymbolTable.cpp.
References mlir::failure(), mlir::Identifier::get(), mlir::FlatSymbolRefAttr::get(), mlir::Operation::getContext(), getNameIfSymbol(), mlir::Operation::getParentOp(), mlir::SymbolTable::getSymbolAttrName(), mlir::Operation::hasTrait(), mlir::Operation::isAncestor(), and mlir::success().
Referenced by collectSymbolScopes().
generateNewRefAttr()
static SymbolRefAttr generateNewRefAttr (SymbolRefAttr oldAttr, FlatSymbolRefAttr newLeafAttr) static
Generates a new symbol reference attribute with a new leaf reference.
Definition at line 859 of file SymbolTable.cpp.
Referenced by replaceAllSymbolUsesImpl().
getNameIfSymbol() [1/2]
static StringAttr getNameIfSymbol (Operation * op) static
Returns the string name of the given symbol, or null if this is not a symbol.
Definition at line 27 of file SymbolTable.cpp.
References mlir::Operation::getAttrOfType(), and mlir::SymbolTable::getSymbolAttrName().
Referenced by collectValidReferencesFor(), mlir::SymbolTable::erase(), mlir::SymbolTable::getSymbolName(), mlir::SymbolTable::lookupSymbolIn(), and mlir::SymbolTable::SymbolTable().
getNameIfSymbol() [2/2]
static StringAttr getNameIfSymbol (Operation * op, Identifier symbolAttrNameId) static
Definition at line 30 of file SymbolTable.cpp.
References mlir::Operation::getAttrOfType().
getSymbolUsesImpl() [1/2]
template<typename FromT > static Optional<SymbolTable::UseRange> getSymbolUsesImpl (FromT from) static
The implementation of SymbolTable::getSymbolUses below.
Definition at line 711 of file SymbolTable.cpp.
References mlir::WalkResult::advance(), and walkSymbolUses().
Referenced by mlir::SymbolTable::getSymbolUses().
getSymbolUsesImpl() [2/2]
template<typename SymbolT , typename IRUnitT > static Optional<SymbolTable::UseRange> getSymbolUsesImpl (SymbolT symbol, IRUnitT * limit) static
The implementation of SymbolTable::getSymbolUses below.
Definition at line 740 of file SymbolTable.cpp.
References collectSymbolScopes().
isPotentiallyUnknownSymbolTable()
static bool isPotentiallyUnknownSymbolTable (Operation * op) static
Return true if the given operation is unknown and may potentially define a symbol table.
Definition at line 21 of file SymbolTable.cpp.
References mlir::Operation::getDialect(), and mlir::Operation::getNumRegions().
Referenced by mlir::SymbolTable::getNearestSymbolTable(), and walkSymbolUses().
isReferencePrefixOf()
static bool isReferencePrefixOf (SymbolRefAttr subRef, SymbolRefAttr ref) static
Returns true if the given reference 'SubRef' is a sub reference of the reference 'ref', i.e.
'ref' is a further qualified reference.
Definition at line 690 of file SymbolTable.cpp.
Referenced by replaceAllSymbolUsesImpl().
lookupSymbolInImpl()
static LogicalResult lookupSymbolInImpl (Operation * symbolTableOp, SymbolRefAttr symbol, SmallVectorImpl< Operation *> & symbols, function_ref< Operation *(Operation *, StringAttr)> lookupSymbolFn) static
Internal implementation of lookupSymbolIn that allows for specialized implementations of the lookup function.
Definition at line 323 of file SymbolTable.cpp.
References mlir::failure(), mlir::Operation::getAttr(), mlir::Operation::hasTrait(), and mlir::success().
Referenced by mlir::SymbolTable::lookupSymbolIn(), and mlir::SymbolTableCollection::lookupSymbolIn().
rebuildAttrAfterRAUW()
static Attribute rebuildAttrAfterRAUW (Attribute container, ArrayRef< std::pair< SmallVector< int, 1 >, SymbolRefAttr >> accesses, unsigned depth) static
Rebuild the given attribute container after replacing all references to a symbol with the updated attribute in 'accesses'.
Definition at line 814 of file SymbolTable.cpp.
References mlir::Attribute::cast(), mlir::Attribute::dyn_cast(), and mlir::Attribute::getContext().
Referenced by replaceAllSymbolUsesImpl().
replaceAllSymbolUsesImpl()
template<typename SymbolT , typename IRUnitT > static LogicalResult replaceAllSymbolUsesImpl (SymbolT symbol, StringAttr newSymbol, IRUnitT * limit) static
The implementation of SymbolTable::replaceAllSymbolUses below.
Definition at line 871 of file SymbolTable.cpp.
References mlir::WalkResult::advance(), collectSymbolScopes(), mlir::failure(), generateNewRefAttr(), mlir::FlatSymbolRefAttr::get(), mlir::Operation::getAttrDictionary(), mlir::SymbolTable::SymbolUse::getSymbolRef(), mlir::SymbolTable::SymbolUse::getUser(), isReferencePrefixOf(), rebuildAttrAfterRAUW(), mlir::Operation::setAttrs(), and mlir::success().
Referenced by mlir::SymbolTable::replaceAllSymbolUses().
symbolKnownUseEmptyImpl()
template<typename SymbolT , typename IRUnitT > static bool symbolKnownUseEmptyImpl (SymbolT symbol, IRUnitT * limit) static
The implementation of SymbolTable::symbolKnownUseEmpty below.
Definition at line 779 of file SymbolTable.cpp.
References mlir::WalkResult::advance(), and collectSymbolScopes().
Referenced by mlir::SymbolTable::symbolKnownUseEmpty().
walkSymbolRefs()
static WalkResult walkSymbolRefs (Operation * op, function_ref< WalkResult(SymbolTable::SymbolUse, ArrayRef< int >)> callback) static
Walk all of the symbol references within the given operation, invoking the provided callback for each found use.
The callbacks takes as arguments: the use of the symbol, and the nested access chain to the attribute within the operation dictionary. An access chain is a set of indices into nested container attributes. For example, a symbol use in an attribute dictionary that looks like the following:
{use = [{other_attr, }]}
May have the following access chain:
[0, 0, 1]
Check for a nested container attribute, these will also need to be walked.
Definition at line 478 of file SymbolTable.cpp.
References mlir::WalkResult::advance(), mlir::Attribute::cast(), mlir::Attribute::dyn_cast(), mlir::Operation::getAttrDictionary(), mlir::WalkResult::interrupt(), and mlir::WalkResult::wasInterrupted().
Referenced by walkSymbolUses().
walkSymbolTable()
static Optional<WalkResult> walkSymbolTable (MutableArrayRef< Region > regions, function_ref< Optional< WalkResult >(Operation *)> callback) static
Walk all of the operations within the given set of regions, without traversing into any nested symbol tables.
Stops walking if the result of the callback is anything other than WalkResult::advance.
Definition at line 80 of file SymbolTable.cpp.
References mlir::WalkResult::advance().
Referenced by mlir::detail::verifySymbolTable(), and walkSymbolUses().
walkSymbolUses() [1/2]
static Optional<WalkResult> walkSymbolUses (MutableArrayRef< Region > regions, function_ref< WalkResult(SymbolTable::SymbolUse, ArrayRef< int >)> callback) static
Walk all of the uses, for any symbol, that are nested within the given regions, invoking the provided callback for each.
This does not traverse into any nested symbol tables.
Definition at line 536 of file SymbolTable.cpp.
References isPotentiallyUnknownSymbolTable(), walkSymbolRefs(), and walkSymbolTable().
Referenced by getSymbolUsesImpl(), and walkSymbolUses().
walkSymbolUses() [2/2]
static Optional<WalkResult> walkSymbolUses (Operation * from, function_ref< WalkResult(SymbolTable::SymbolUse, ArrayRef< int >)> callback) static
Walk all of the uses, for any symbol, that are nested within the given operation 'from', invoking the provided callback for each.
This does not traverse into any nested symbol tables.
Definition at line 550 of file SymbolTable.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getRegions(), mlir::Operation::hasTrait(), mlir::WalkResult::interrupt(), isPotentiallyUnknownSymbolTable(), value, mlir::detail::walk(), walkSymbolRefs(), and walkSymbolUses().