MLIR: lib/Dialect/Vector/VectorTransforms.cpp File Reference
VectorTransforms.cpp File Reference
#include <type_traits>
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorTransforms.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Types.h"
#include "mlir/Interfaces/VectorInterfaces.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct PointwiseExtractPattern
Canonicalize an extract_map using the result of a pointwise operation.
struct ContractExtractPattern
Canonicalize an extract_map using the result of a contract operation.
struct TransferReadExtractPattern
Converts TransferRead op used by ExtractMap op into a smaller dimension TransferRead.
struct TransferWriteInsertPattern
struct TransferReadToVectorLoadLowering
Progressive lowering of transfer_read.
struct VectorLoadToMemrefLoadLowering
Replace a scalar vector.load with a memref.load.
struct VectorStoreToMemrefStoreLowering
Replace a scalar vector.store with a memref.store.
struct TransferWriteToVectorStoreLowering
Progressive lowering of transfer_write.
struct TransferReadPermutationLowering
Lower transfer_read op with permutation into a transfer_read with a permutation map composed of leading zeros followed by a minor identiy + vector.transpose op.
struct TransferWritePermutationLowering
Lower transfer_write op with permutation into a transfer_write with a minor identity permutation map.
struct TransferOpReduceRank
Lower transfer_read op with broadcast in the leading dimensions into transfer_read of lower rank + vector.broadcast.
struct CastAwayExtractStridedSliceLeadingOneDim
struct CastAwayInsertStridedSliceLeadingOneDim
struct CastAwayTransferReadLeadingOneDim
struct CastAwayTransferWriteLeadingOneDim
struct CastAwayBroadcastLeadingOneDim< BroadCastType >
class CastAwayElementwiseLeadingOneDim
struct BubbleDownVectorBitCastForExtract
struct BubbleDownBitCastForStridedSliceExtract
struct BubbleUpBitCastForStridedSliceInsert
struct MaterializeTransferMask< ConcreteOp >
class VectorCreateMaskOpConversion
Conversion pattern for a vector.create_mask (1-D only).
class DropInnerMostUnitDims
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "vector-to-vector"
Functions
static Optional< int64_t > getResultIndex (AffineMap map, int64_t index)
static SmallVector< Attribute, 4 > adjustIter (ArrayAttr iteratorTypes, int64_t index)
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter &rewriter)
static Type adjustType (VectorType tp, int64_t index)
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Operation * cloneOpWithOperandsAndTypes (OpBuilder &builder, Location loc, Operation *op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes)
static Optional< SmallVector< int64_t, 4 > > getTargetShape (const vector::UnrollVectorOptions &options, Operation *op)
Return the target shape for unrolling for the given op.
static SmallVector< int64_t, 4 > getVectorOffset (ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, int64_t index)
During unrolling from originalShape to targetShape return the offset for the slice index.
static SmallVector< Value > sliceTransferIndices (int64_t index, ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, ArrayRef< Value > indices, AffineMap permutationMap, Location loc, OpBuilder &builder)
Compute the indices of the slice index for a tranfer op.
template<typename IntType >
static SmallVector< IntType, 4 > extractVector (ArrayAttr arrayAttr)
static Value createAdd (Location loc, Value x, Value y, bool isInt, PatternRewriter &rewriter)
Creates an AddIOp if isInt is true otherwise create an arith::AddFOp using operands x and y.
static Value createMul (Location loc, Value x, Value y, bool isInt, PatternRewriter &rewriter)
Creates a MulIOp if isInt is true otherwise create an MulFOp using operands x andy`.
static Optional< int64_t > extractConstantIndex (Value v)
static Value createFoldedSLE (OpBuilder &b, Value v, Value ub)
static Value createInBoundsCond (OpBuilder &b, VectorTransferOpInterface xferOp)
static MemRefType getCastCompatibleMemRefType (MemRefType aT, MemRefType bT)
Given two MemRefTypes aT and bT, return a MemRefType to which both can be cast.
static std::pair< Value, Value > createSubViewIntersection (OpBuilder &b, VectorTransferOpInterface xferOp, Value alloc)
Operates under a scoped context to build the intersection between the view xferOp.source() @ xferOp.indices() and the view alloc.
static scf::IfOp createFullPartialLinalgCopy (OpBuilder &b, vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
static scf::IfOp createFullPartialVectorTransferRead (OpBuilder &b, vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
static ValueRange getLocationToWriteFullVec (OpBuilder &b, vector::TransferWriteOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
static void createFullPartialLinalgCopy (OpBuilder &b, vector::TransferWriteOp xferOp, Value inBoundsCond, Value alloc)
Given an xferOp for which:
static void createFullPartialVectorTransferWrite (OpBuilder &b, vector::TransferWriteOp xferOp, Value inBoundsCond, Value alloc)
Given an xferOp for which:
static ArrayAttr transposeInBoundsAttr (OpBuilder &builder, ArrayAttr attr, const SmallVector< unsigned > &permutation)
Transpose a vector transfer op's in_bounds attribute according to given indices.
static VectorType trimLeadingOneDims (VectorType oldType)
static SmallVector< int64_t, 4 > getIntValueVector (ArrayAttr arrayAttr)
static Value createCastToIndexLike (PatternRewriter &rewriter, Location loc, Type targetType, Value value)
static Value buildVectorComparison (PatternRewriter &rewriter, Operation *op, bool enableIndexOptimizations, int64_t dim, Value b, Value *off=nullptr)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-to-vector"
Definition at line 48 of file VectorTransforms.cpp.
Function Documentation
adjustIter()
static SmallVector<Attribute, 4> adjustIter (ArrayAttr iteratorTypes, int64_t index) static
Definition at line 63 of file VectorTransforms.cpp.
References mlir::detail::enumerate().
adjustMap()
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter & rewriter) static
Definition at line 76 of file VectorTransforms.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumDims(), and mlir::AffineMap::getNumResults().
adjustType()
static Type adjustType (VectorType tp, int64_t index) static
Definition at line 93 of file VectorTransforms.cpp.
Referenced by reshapeLoad(), and reshapeStore().
buildVectorComparison()
static Value buildVectorComparison (PatternRewriter & rewriter, Operation * op, bool enableIndexOptimizations, int64_t dim, Value b, Value * off = nullptr) static
Definition at line 3616 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), createCastToIndexLike(), mlir::Builder::getI32Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Operation::getLoc(), and mlir::Value::getType().
Referenced by MaterializeTransferMask< ConcreteOp >::matchAndRewrite(), and VectorCreateMaskOpConversion::matchAndRewrite().
cloneOpWithOperandsAndTypes()
static Operation* cloneOpWithOperandsAndTypes (OpBuilder & builder, Location loc, Operation * op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes) static
Definition at line 168 of file VectorTransforms.cpp.
Referenced by PointwiseExtractPattern::matchAndRewrite(), and ContractExtractPattern::matchAndRewrite().
createAdd()
static Value createAdd (Location loc, Value x, Value y, bool isInt, PatternRewriter & rewriter) static
Creates an AddIOp if isInt is true otherwise create an arith::AddFOp using operands x and y.
Definition at line 1316 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
createCastToIndexLike()
static Value createCastToIndexLike (PatternRewriter & rewriter, Location loc, Type targetType, Value value) static
Definition at line 3588 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::Value::getType(), mlir::Type::isIndex(), and value.
Referenced by buildVectorComparison().
createFoldedSLE()
static Value createFoldedSLE (OpBuilder & b, Value v, Value ub) static
Definition at line 1940 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), extractConstantIndex(), and mlir::Value::getLoc().
Referenced by createInBoundsCond().
createFullPartialLinalgCopy() [1/2]
static scf::IfOp createFullPartialLinalgCopy (OpBuilder & b, vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   %view = memref.cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %2 = linalg.fill(%pad, %alloc)
   %3 = subview %view [...][...][...]
   %4 = subview %alloc [0, 0] [...] [...]
   linalg.copy(%3, %4)
   %5 = memref.cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %5, ... : compatibleMemRefType, index, index
}
Return the produced scf::IfOp.
Definition at line 2099 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createFullPartialLinalgCopy() [2/2]
static void createFullPartialLinalgCopy (OpBuilder & b, vector::TransferWriteOp xferOp, Value inBoundsCond, Value alloc) static
Given an xferOp for which:
inBoundsCond has been computed.
a memref of single vector alloc has been allocated.
it originally wrote to view Produce IR resembling:
 %notInBounds = arith.xori %inBounds, %true
 scf.if (%notInBounds) {
   %3 = subview %alloc [...][...][...]
   %4 = subview %view [0, 0][...][...]
   linalg.copy(%3, %4)
}
Definition at line 2244 of file VectorTransforms.cpp.
References mlir::ImplicitLocOpBuilder::create(), and createSubViewIntersection().
createFullPartialVectorTransferRead()
static scf::IfOp createFullPartialVectorTransferRead (OpBuilder & b, vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   memref.cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %2 = vector.transfer_read %view[...], %pad : memref<A...>, vector<...>
   %3 = vector.type_cast %extra_alloc :
     memref<...> to memref<vector<...>>
   store %2, %3[] : memref<vector<...>>
   %4 = memref.cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %4, ... : compatibleMemRefType, index, index
}
Return the produced scf::IfOp.
Definition at line 2150 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createFullPartialVectorTransferWrite()
static void createFullPartialVectorTransferWrite (OpBuilder & b, vector::TransferWriteOp xferOp, Value inBoundsCond, Value alloc) static
Given an xferOp for which:
inBoundsCond has been computed.
a memref of single vector alloc has been allocated.
it originally wrote to view Produce IR resembling:
 %notInBounds = arith.xori %inBounds, %true
 scf.if (%notInBounds) {
   %2 = load %alloc : memref<vector<...>>
   vector.transfer_write %2, %view[...] : memref<A...>, vector<...>
}
Definition at line 2270 of file VectorTransforms.cpp.
References mlir::ImplicitLocOpBuilder::create(), and mlir::BlockAndValueMapping::map().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createInBoundsCond()
static Value createInBoundsCond (OpBuilder & b, VectorTransferOpInterface xferOp) static
Definition at line 1950 of file VectorTransforms.cpp.
References mlir::ImplicitLocOpBuilder::create(), createFoldedSLE(), mlir::vector::createOrFoldDimOp(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), and mlir::makeComposedAffineApply().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createMul()
static Value createMul (Location loc, Value x, Value y, bool isInt, PatternRewriter & rewriter) static
Creates a MulIOp if isInt is true otherwise create an MulFOp using operands x andy`.
Definition at line 1325 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
createSubViewIntersection()
static std::pair<Value, Value> createSubViewIntersection (OpBuilder & b, VectorTransferOpInterface xferOp, Value alloc) static
Operates under a scoped context to build the intersection between the view xferOp.source() @ xferOp.indices() and the view alloc.
Definition at line 2041 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::Type::cast(), mlir::vector::createOrFoldDimOp(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), and mlir::AffineMap::inferFromExprList().
Referenced by createFullPartialLinalgCopy().
extractConstantIndex()
static Optional<int64_t> extractConstantIndex (Value v) static
Definition at line 1928 of file VectorTransforms.cpp.
References mlir::Value::getDefiningOp().
Referenced by createFoldedSLE().
extractVector()
template<typename IntType > static SmallVector<IntType, 4> extractVector (ArrayAttr arrayAttr) static
Definition at line 244 of file VectorTransforms.cpp.
References mlir::computeMaxLinearIndex(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failure(), getTargetShape(), getVectorOffset(), mlir::Builder::getZeroAttr(), options, mlir::RewriterBase::replaceOp(), mlir::shapeRatio(), sliceTransferIndices(), and mlir::success().
getCastCompatibleMemRefType()
static MemRefType getCastCompatibleMemRefType (MemRefType aT, MemRefType bT) static
Given two MemRefTypes aT and bT, return a MemRefType to which both can be cast.
If the MemRefTypes don't have the same rank or are not strided, return null; otherwise:
if aT and bT are cast-compatible, return aT.
else return a new MemRefType obtained by iterating over the shape and strides and: a. keeping the ones that are static and equal across aT and bT. b. using a dynamic shape and/or stride for the dimensions that don't agree.
Definition at line 2007 of file VectorTransforms.cpp.
References mlir::failed(), mlir::getStridesAndOffset(), and mlir::makeStridedLinearLayoutMap().
Referenced by mlir::vector::splitFullAndPartialTransfer().
getIntValueVector()
static SmallVector<int64_t, 4> getIntValueVector (ArrayAttr arrayAttr) static
Definition at line 3351 of file VectorTransforms.cpp.
Referenced by BubbleDownBitCastForStridedSliceExtract::matchAndRewrite(), and BubbleUpBitCastForStridedSliceInsert::matchAndRewrite().
getLocationToWriteFullVec()
static ValueRange getLocationToWriteFullVec (OpBuilder & b, vector::TransferWriteOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   memref.cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %3 = vector.type_cast %extra_alloc :
     memref<...> to memref<vector<...>>
   %4 = memref.cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %4, ... : compatibleMemRefType, index, index
}
Definition at line 2201 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::vector::splitFullAndPartialTransfer().
getResultIndex()
static Optional<int64_t> getResultIndex (AffineMap map, int64_t index) static
Definition at line 53 of file VectorTransforms.cpp.
References mlir::AffineMap::getDimPosition(), and mlir::AffineMap::getNumResults().
getTargetShape()
static Optional<SmallVector<int64_t, 4> > getTargetShape (const vector::UnrollVectorOptions & options, Operation * op) static
Return the target shape for unrolling for the given op.
Return llvm::None if the op shouldn't be or cannot be unrolled.
Definition at line 180 of file VectorTransforms.cpp.
References mlir::failed(), mlir::vector::UnrollVectorOptions::filterConstraint, mlir::vector::UnrollVectorOptions::nativeShape, and mlir::shapeRatio().
Referenced by extractVector().
getVectorOffset()
static SmallVector<int64_t, 4> getVectorOffset (ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, int64_t index) static
During unrolling from originalShape to targetShape return the offset for the slice index.
Definition at line 204 of file VectorTransforms.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeStrides(), and mlir::delinearize().
Referenced by extractVector(), and sliceTransferIndices().
reshapeLoad()
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 113 of file VectorTransforms.cpp.
References adjustType(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), and mlir::Builder::getZeroAttr().
reshapeStore()
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 141 of file VectorTransforms.cpp.
References adjustType(), mlir::OpBuilder::create(), and mlir::Builder::getI64ArrayAttr().
sliceTransferIndices()
static SmallVector<Value> sliceTransferIndices (int64_t index, ArrayRef< int64_t > originalShape, ArrayRef< int64_t > targetShape, ArrayRef< Value > indices, AffineMap permutationMap, Location loc, OpBuilder & builder) static
Compute the indices of the slice index for a tranfer op.
Definition at line 217 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getResults(), getVectorOffset(), and map().
Referenced by extractVector().
transposeInBoundsAttr()
static ArrayAttr transposeInBoundsAttr (OpBuilder & builder, ArrayAttr attr, const SmallVector< unsigned > & permutation) static
Transpose a vector transfer op's in_bounds attribute according to given indices.
Definition at line 2866 of file VectorTransforms.cpp.
References mlir::Builder::getBoolArrayAttr().
Referenced by TransferReadPermutationLowering::matchAndRewrite(), and TransferWritePermutationLowering::matchAndRewrite().
trimLeadingOneDims()
static VectorType trimLeadingOneDims (VectorType oldType) static
Definition at line 3099 of file VectorTransforms.cpp.
Referenced by CastAwayExtractStridedSliceLeadingOneDim::matchAndRewrite(), CastAwayInsertStridedSliceLeadingOneDim::matchAndRewrite(), CastAwayTransferReadLeadingOneDim::matchAndRewrite(), CastAwayTransferWriteLeadingOneDim::matchAndRewrite(), CastAwayBroadcastLeadingOneDim< BroadCastType >::matchAndRewrite(), and CastAwayElementwiseLeadingOneDim::matchAndRewrite().
Variable Documentation
strRef
StringRef strRef
Definition at line 1441 of file VectorTransforms.cpp.
Referenced by mlir::StructuredGenerator< StructuredOpInterface >::IteratorType::isOfType(), and twineToStrRef().